// GENERATED FILE — do not edit. Regenerate via: cd ui && pnpm types:gen
// Source: http://localhost:8000/openapi.json
//
// Prerequisite: the backend must be running (make up) so /openapi.json is reachable.
// CI does NOT regenerate this file — the committed version is the source of truth
// for the PR. If you need a fresh schema, run `cd ui && pnpm types:gen` locally.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Probe each subsystem in parallel and return the documented JSON shape.
     *
     *     Args:
     *         settings: Application settings (DB URL, ES/OS URLs, OpenAI base URL, etc.)
     *         redis_client: Redis client for ping probe + capability-cache read
     *         es_client: shared httpx client for ES + OpenSearch HTTP probes
     *         db: Async DB session for the registered-clusters aggregate (Story 3.5)
     *
     *     Returns:
     *         JSONResponse with the HealthResponse body and HTTP 200 (healthy) or 503 (degraded).
     */
    get: operations['healthz_healthz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/clusters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Clusters
     * @description List clusters with cursor pagination + ``X-Total-Count`` header.
     */
    get: operations['list_clusters_api_v1_clusters_get'];
    put?: never;
    /**
     * Create Cluster
     * @description Register a cluster (FR-5 / AC-1).
     */
    post: operations['create_cluster_api_v1_clusters_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/clusters/{cluster_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Cluster Detail
     * @description Return cluster row + cached/fresh health probe.
     */
    get: operations['get_cluster_detail_api_v1_clusters__cluster_id__get'];
    put?: never;
    post?: never;
    /**
     * Delete Cluster
     * @description Soft-delete a cluster (AC-8). Returns 204 with no body.
     */
    delete: operations['delete_cluster_api_v1_clusters__cluster_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/clusters/{cluster_id}/schema': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Cluster Schema
     * @description Return the field schema for ``target`` (FR-4 / AC-2).
     */
    get: operations['get_cluster_schema_api_v1_clusters__cluster_id__schema_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/clusters/{cluster_id}/run_query': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run Query
     * @description Execute one query DSL fragment against the cluster (FR-6 / AC-3).
     */
    post: operations['run_query_api_v1_clusters__cluster_id__run_query_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/query-templates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Query Templates
     * @description List query templates with cursor pagination + X-Total-Count header.
     */
    get: operations['list_query_templates_api_v1_query_templates_get'];
    put?: never;
    /**
     * Create Query Template
     * @description Register a query template (FR-2 + AC-7).
     *
     *     AC-7: a body containing ``{{ os.system('rm -rf /') }}`` surfaces as
     *     400 ``INVALID_TEMPLATE_SYNTAX`` (the AST walk catches the ``Call``
     *     node before reaching the meta-vars cross-check that would otherwise
     *     classify ``os`` as ``UndeclaredParamUsed``).
     */
    post: operations['create_query_template_api_v1_query_templates_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/query-templates/{template_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Query Template Detail
     * @description Return a query template by id.
     */
    get: operations['get_query_template_detail_api_v1_query_templates__template_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/query-sets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Query Sets
     * @description List query sets with cursor pagination + X-Total-Count.
     */
    get: operations['list_query_sets_api_v1_query_sets_get'];
    put?: never;
    /**
     * Create Query Set
     * @description Register a query set under a cluster (FR-3).
     */
    post: operations['create_query_set_api_v1_query_sets_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/query-sets/{query_set_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Query Set Detail
     * @description Return a query set by id (includes ``query_count``).
     */
    get: operations['get_query_set_detail_api_v1_query_sets__query_set_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/query-sets/{query_set_id}/queries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Add Queries
     * @description Bulk-add queries to a set (FR-3 + AC-8).
     *
     *     Dispatches on Content-Type:
     *
     *     * ``application/json`` → :class:`BulkQueriesJsonRequest` Pydantic-parse.
     *     * ``text/csv`` → :func:`parse_queries_csv` (AC-8).
     *
     *     Other content types → 415-equivalent surfaced as 400 ``INVALID_CSV``
     *     (the documented error code for content-type-mismatch in spec §7.5).
     */
    post: operations['bulk_add_queries_api_v1_query_sets__query_set_id__queries_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/studies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Studies
     * @description List studies with cursor pagination + X-Total-Count.
     *
     *     ``?status=`` is typed as :data:`StudyStatusWire` so FastAPI returns
     *     422 ``VALIDATION_ERROR`` for unsupported values rather than silently
     *     returning an empty list (C3-F2 GPT-5.5 cycle-3 fix).
     */
    get: operations['list_studies_api_v1_studies_get'];
    put?: never;
    /**
     * Create Study
     * @description Create a study (FR-1 + AC-1) and enqueue the orchestrator job.
     */
    post: operations['create_study_api_v1_studies_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/studies/{study_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Study Detail
     * @description Return a study by id (includes ``trials_summary``).
     */
    get: operations['get_study_detail_api_v1_studies__study_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/studies/{study_id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Study
     * @description Cancel a study (FR-1 + AC-3).
     *
     *     Routes through :func:`services.study_state.cancel_study`. The
     *     orchestrator detects the new status on its next poll tick and drains
     *     in-flight trials. Cancelling an already-terminal study (completed /
     *     cancelled / failed) raises ``InvalidStateTransition`` → 409.
     */
    post: operations['cancel_study_api_v1_studies__study_id__cancel_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/studies/{study_id}/trials': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Study Trials
     * @description List trials in a study (FR-6).
     *
     *     Sort variants per spec §7.4: ``primary_metric_desc`` (default),
     *     ``primary_metric_asc``, ``created_at_desc``, ``created_at_asc``,
     *     ``optuna_trial_number_asc``.
     */
    get: operations['list_study_trials_api_v1_studies__study_id__trials_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/judgments/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Judgments
     * @description Create a judgment_lists row + enqueue the worker.
     *
     *     Preflight order (matches spec FR-3 + GPT-5.5 cycles 1/2):
     *
     *     A. ``OPENAI_NOT_CONFIGURED`` — key missing.
     *     B. ``LLM_PROVIDER_INCAPABLE`` — capability cache miss OR
     *        ``structured_output != ok`` (strict per spec FR-3).
     *     B.1. ``UNKNOWN_MODEL_PRICING`` — :data:`Settings.openai_model` has no
     *        cost_model entry (otherwise the budget gate is silently defeated).
     *     C. ``OPENAI_BUDGET_EXCEEDED`` — pre-call peek already >= budget.
     *     D. FK resolution (cluster / template / query_set).
     *     E. Oversized query set (>10K) → 422 VALIDATION_ERROR.
     *     F. INSERT; commit; best-effort enqueue.
     */
    post: operations['generate_judgments_api_v1_judgments_generate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/judgment-lists/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import Judgment List
     * @description Create a judgment_lists row with status='complete' + bulk-insert judgments.
     *
     *     Tutorial path; no OpenAI involvement. Every supplied judgment must
     *     reference a ``query_id`` that exists in ``body.query_set_id`` —
     *     mismatches → 400 ``QUERY_NOT_IN_SET``.
     */
    post: operations['import_judgment_list_api_v1_judgment_lists_import_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/judgment-lists': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Judgment Lists Endpoint
     * @description List judgment lists, newest-first with cursor pagination.
     */
    get: operations['list_judgment_lists_endpoint_api_v1_judgment_lists_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/judgment-lists/{judgment_list_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Judgment List Endpoint */
    get: operations['get_judgment_list_endpoint_api_v1_judgment_lists__judgment_list_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/judgment-lists/{judgment_list_id}/judgments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Judgments Endpoint */
    get: operations['list_judgments_endpoint_api_v1_judgment_lists__judgment_list_id__judgments_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/judgment-lists/{judgment_list_id}/judgments/{judgment_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Override Judgment
     * @description Replace an LLM rating with a human override (UPSERT-replace).
     */
    patch: operations['override_judgment_api_v1_judgment_lists__judgment_list_id__judgments__judgment_id__patch'];
    trace?: never;
  };
  '/api/v1/judgment-lists/{judgment_list_id}/calibration': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Calibrate Judgment List
     * @description Compute Cohen's + weighted kappa from supplied human samples.
     *
     *     Pairs are built by joining each sample with the existing
     *     ``source='llm'`` judgment at ``(query_id, doc_id)`` — overridden rows
     *     (``source='human'``) are excluded (per spec FR-5 + GPT-5.5 cycle 1 F12).
     */
    post: operations['calibrate_judgment_list_api_v1_judgment_lists__judgment_list_id__calibration_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/studies/{study_id}/digest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Study Digest
     * @description Fetch the digest for a completed study.
     *
     *     Returns 404 ``DIGEST_NOT_READY`` (``retryable=true``) when:
     *     - the study is not in ``status='completed'``, OR
     *     - the study is completed but the worker hasn't written the digest yet
     *       (worker lag, or a worker-side terminal failure like
     *       ``OPENAI_NOT_CONFIGURED`` deferred the run).
     */
    get: operations['get_study_digest_api_v1_studies__study_id__digest_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/proposals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Proposals Endpoint
     * @description List proposals with cursor pagination + status + cluster_id filters.
     */
    get: operations['list_proposals_endpoint_api_v1_proposals_get'];
    put?: never;
    /**
     * Create Manual Proposal
     * @description Manually create a proposal (chat-agent hand-crafted tweaks).
     *
     *     ``study_id`` and ``study_trial_id`` are NULL for manual proposals.
     *     Validates FK targets (cluster + template exist) before insert.
     */
    post: operations['create_manual_proposal_api_v1_proposals_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/proposals/{proposal_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Proposal Endpoint */
    get: operations['get_proposal_endpoint_api_v1_proposals__proposal_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/proposals/{proposal_id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reject Proposal Endpoint
     * @description AC-5: ``pending → rejected`` transition; 409 INVALID_STATE_TRANSITION otherwise.
     */
    post: operations['reject_proposal_endpoint_api_v1_proposals__proposal_id__reject_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/proposals/{proposal_id}/open_pr': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Open Pr Endpoint
     * @description Enqueue the ``open_pr`` worker for an operator-approved proposal.
     *
     *     Preflight order matches spec FR-1:
     *
     *     1. Proposal exists → else 404 ``PROPOSAL_NOT_FOUND``.
     *     2. Proposal status is ``pending`` → else 409 ``INVALID_STATE_TRANSITION``
     *        (AC-6).
     *     3. Cluster has a ``config_repo_id`` → else 422 ``CLUSTER_HAS_NO_CONFIG_REPO``.
     *     4. Per-repo PAT readable from ``./secrets/{auth_ref}`` → else 503
     *        ``GITHUB_NOT_CONFIGURED`` (AC-2).
     *     5. Enqueue with deterministic ``_job_id=f"open_pr:{proposal_id}"``
     *        for dedup (AC-12). On enqueue failure (Arq pool absent or raise)
     *        return 503 ``QUEUE_UNAVAILABLE`` per cycle-2 F5 — there is NO
     *        boot-scan recovery for this worker, so a silent enqueue drop
     *        would leave the proposal pending forever with no ``pr_open_error``.
     */
    post: operations['open_pr_endpoint_api_v1_proposals__proposal_id__open_pr_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/config-repos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Config Repos Endpoint
     * @description Cursor-paginated config-repo list, newest first.
     */
    get: operations['list_config_repos_endpoint_api_v1_config_repos_get'];
    put?: never;
    /**
     * Create Config Repo Endpoint
     * @description Register a new config repo. ``provider`` is server-derived from ``repo_url``.
     *
     *     Preflight order matches spec FR-3:
     *
     *     1. ``validate_repo_url(repo_url)`` → 400 ``UNSUPPORTED_PROVIDER`` for
     *        non-GitHub URLs (AC-8). GitLab + Bitbucket arrive at MVP3.
     *     2. ``./secrets/{auth_ref}`` must exist → else 400 ``AUTH_REF_NOT_FOUND``
     *        (AC-9). The contents check defers to the worker — operators may
     *        populate the file between registration and first PR-open.
     *     3. ``name`` uniqueness check → 409 ``CONFIG_REPO_NAME_TAKEN`` on collision.
     *     4. Insert with server-derived ``provider="github"``.
     */
    post: operations['create_config_repo_endpoint_api_v1_config_repos_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/config-repos/{config_repo_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Config Repo Endpoint
     * @description Detail by id; 404 ``CONFIG_REPO_NOT_FOUND`` if missing.
     */
    get: operations['get_config_repo_endpoint_api_v1_config_repos__config_repo_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * BulkQueriesResponse
     * @description ``POST /api/v1/query-sets/{id}/queries`` response.
     */
    BulkQueriesResponse: {
      /** Added */
      added: number;
    };
    /**
     * CalibrationResponse
     * @description Calibration endpoint response.
     *
     *     Mirrors :class:`backend.app.eval.calibration.CalibrationResult` —
     *     persisted as ``judgment_lists.calibration`` JSONB.
     */
    CalibrationResponse: {
      /** Cohens Kappa */
      cohens_kappa: number | null;
      /** Weighted Kappa */
      weighted_kappa: number | null;
      /** Per Class */
      per_class: {
        [key: string]: number;
      };
      /** N Samples */
      n_samples: number;
      /** Warning */
      warning: string | null;
    };
    /**
     * CalibrationSample
     * @description One row in :class:`CalibrationSamplesRequest`.
     */
    CalibrationSample: {
      /** Query Id */
      query_id: string;
      /** Doc Id */
      doc_id: string;
      /**
       * Rating
       * @enum {integer}
       */
      rating: 0 | 1 | 2 | 3;
    };
    /**
     * CalibrationSamplesRequest
     * @description Body for ``POST /api/v1/judgment-lists/{id}/calibration`` (Story 3.5).
     */
    CalibrationSamplesRequest: {
      /** Human Samples */
      human_samples: components['schemas']['CalibrationSample'][];
    };
    /**
     * ClusterAggregateHealth
     * @description Aggregate counts for the ``elasticsearch_clusters`` /healthz field (Story 3.5).
     *
     *     Per spec §2: probes only the *registered* user clusters (from the DB),
     *     NOT the local Compose ES/OpenSearch — those have their own subsystem
     *     fields. ``status`` is a count derived from the cached ``cluster:health:*``
     *     entries; missing-cache or red/unreachable clusters are counted as
     *     ``unreachable``.
     */
    ClusterAggregateHealth: {
      /** Registered */
      registered: number;
      /** Healthy */
      healthy: number;
      /** Unreachable */
      unreachable: number;
    };
    /**
     * ClusterDetail
     * @description ``GET /api/v1/clusters/{id}`` response.
     */
    ClusterDetail: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Engine Type
       * @enum {string}
       */
      engine_type: 'elasticsearch' | 'opensearch';
      /**
       * Environment
       * @enum {string}
       */
      environment: 'prod' | 'staging' | 'dev';
      /** Base Url */
      base_url: string;
      /**
       * Auth Kind
       * @enum {string}
       */
      auth_kind: 'es_apikey' | 'es_basic' | 'opensearch_basic' | 'opensearch_sigv4';
      /** Engine Config */
      engine_config?: {
        [key: string]: unknown;
      } | null;
      /** Notes */
      notes?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      health_check: components['schemas']['HealthCheckResult'];
    };
    /**
     * ClusterListResponse
     * @description Paginated list response.
     */
    ClusterListResponse: {
      /** Data */
      data: components['schemas']['ClusterSummary'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
    };
    /**
     * ClusterSummary
     * @description List-view; drops engine_config + notes for brevity.
     */
    ClusterSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Engine Type
       * @enum {string}
       */
      engine_type: 'elasticsearch' | 'opensearch';
      /**
       * Environment
       * @enum {string}
       */
      environment: 'prod' | 'staging' | 'dev';
      /** Base Url */
      base_url: string;
      /**
       * Auth Kind
       * @enum {string}
       */
      auth_kind: 'es_apikey' | 'es_basic' | 'opensearch_basic' | 'opensearch_sigv4';
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      health_check: components['schemas']['HealthCheckResult'];
    };
    /**
     * ConfigRepoDetail
     * @description ``GET /api/v1/config-repos/{id}`` response + ``POST`` 201 body.
     */
    ConfigRepoDetail: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Provider
       * @constant
       */
      provider: 'github';
      /** Repo Url */
      repo_url: string;
      /** Default Branch */
      default_branch: string;
      /** Pr Base Branch */
      pr_base_branch: string;
      /** Auth Ref */
      auth_ref: string;
      /** Webhook Secret Ref */
      webhook_secret_ref: string | null;
      /** Webhook Registration Error */
      webhook_registration_error: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ConfigReposListResponse
     * @description ``GET /api/v1/config-repos`` response.
     */
    ConfigReposListResponse: {
      /** Data */
      data: components['schemas']['ConfigRepoDetail'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
    };
    /**
     * CreateClusterRequest
     * @description Request body for ``POST /api/v1/clusters``.
     *
     *     See module docstring for the deliberate ``str`` vs ``Literal`` split.
     */
    CreateClusterRequest: {
      /** Name */
      name: string;
      /** Engine Type */
      engine_type: string;
      /**
       * Environment
       * @enum {string}
       */
      environment: 'prod' | 'staging' | 'dev';
      /** Base Url */
      base_url: string;
      /** Auth Kind */
      auth_kind: string;
      /** Credentials Ref */
      credentials_ref: string;
      /** Engine Config */
      engine_config?: {
        [key: string]: unknown;
      } | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * CreateConfigRepoRequest
     * @description Body of ``POST /api/v1/config-repos`` (FR-3).
     *
     *     ``provider`` is server-derived from ``repo_url`` (cycle-2 F4 from
     *     spec review) — NOT in the payload. The validator enforces a strict
     *     GitHub URL pattern; non-GitHub URLs surface as 400
     *     ``UNSUPPORTED_PROVIDER`` at the router layer.
     */
    CreateConfigRepoRequest: {
      /** Name */
      name: string;
      /** Repo Url */
      repo_url: string;
      /**
       * Default Branch
       * @default main
       */
      default_branch: string;
      /**
       * Pr Base Branch
       * @default main
       */
      pr_base_branch: string;
      /** Auth Ref */
      auth_ref: string;
      /** Webhook Secret Ref */
      webhook_secret_ref?: string | null;
    };
    /**
     * CreateJudgmentListGenerateRequest
     * @description Body for ``POST /api/v1/judgments/generate`` (Story 3.1).
     */
    CreateJudgmentListGenerateRequest: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Query Set Id */
      query_set_id: string;
      /** Cluster Id */
      cluster_id: string;
      /** Target */
      target: string;
      /** Current Template Id */
      current_template_id: string;
      /** Rubric */
      rubric: string;
    };
    /**
     * CreateProposalRequest
     * @description Body of ``POST /api/v1/proposals`` (manual proposal creation, FR-4 / AC-6).
     */
    CreateProposalRequest: {
      /** Cluster Id */
      cluster_id: string;
      /** Template Id */
      template_id: string;
      /** Config Diff */
      config_diff: {
        [key: string]: unknown;
      };
      /** Metric Delta */
      metric_delta?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * CreateQuerySetRequest
     * @description ``POST /api/v1/query-sets`` body.
     *
     *     ``cluster_id`` is required because Phase 1's shipped schema has
     *     ``query_sets.cluster_id NOT NULL``. Spec FR-3 wording (``cluster_id?``)
     *     is documented drift tracked at
     *     ``docs/02_product/planned_features/chore_spec_query_set_cluster_id_drift/idea.md``.
     */
    CreateQuerySetRequest: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Cluster Id */
      cluster_id: string;
    };
    /**
     * CreateQueryTemplateRequest
     * @description Request body for ``POST /api/v1/query-templates``.
     */
    CreateQueryTemplateRequest: {
      /** Name */
      name: string;
      /**
       * Engine Type
       * @enum {string}
       */
      engine_type: 'elasticsearch' | 'opensearch';
      /** Body */
      body: string;
      /** Declared Params */
      declared_params?: {
        [key: string]: string;
      };
      /** Parent Id */
      parent_id?: string | null;
    };
    /**
     * CreateStudyRequest
     * @description ``POST /api/v1/studies`` body.
     *
     *     ``search_space`` is validated post-Pydantic-parse via
     *     :class:`backend.app.domain.study.search_space.SearchSpace` so
     *     :exc:`pydantic.ValidationError` produces the spec's 400
     *     ``INVALID_SEARCH_SPACE`` (per Story 3.3 task 2).
     */
    CreateStudyRequest: {
      /** Name */
      name: string;
      /** Cluster Id */
      cluster_id: string;
      /** Target */
      target: string;
      /** Template Id */
      template_id: string;
      /** Query Set Id */
      query_set_id: string;
      /** Judgment List Id */
      judgment_list_id: string;
      /** Search Space */
      search_space: {
        [key: string]: unknown;
      };
      objective: components['schemas']['ObjectiveSpec'];
      config: components['schemas']['StudyConfigSpec'];
    };
    /**
     * DigestResponse
     * @description Body of ``GET /api/v1/studies/{id}/digest`` (FR-3 / AC-3).
     */
    DigestResponse: {
      /** Id */
      id: string;
      /** Study Id */
      study_id: string;
      /** Narrative */
      narrative: string;
      /** Parameter Importance */
      parameter_importance: {
        [key: string]: number;
      };
      /** Recommended Config */
      recommended_config: {
        [key: string]: unknown;
      };
      /** Suggested Followups */
      suggested_followups: string[];
      /** Generated By */
      generated_by: string;
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
    };
    /**
     * FieldSpec
     * @description One field returned by ``get_schema``.
     */
    FieldSpec: {
      /** Name */
      name: string;
      /** Type */
      type: string;
      /** Analyzer */
      analyzer?: string | null;
      /** Doc Count */
      doc_count?: number | null;
    };
    /**
     * GenerateJudgmentsResponse
     * @description Response of ``POST /api/v1/judgments/generate``.
     *
     *     Per GPT-5.5 cycle 1 F5 — the endpoint registers a typed
     *     ``response_model`` so OpenAPI introspection + contract tests can verify
     *     the wire shape.
     */
    GenerateJudgmentsResponse: {
      /** Judgment List Id */
      judgment_list_id: string;
      /**
       * Status
       * @constant
       */
      status: 'generating';
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthCheckResult
     * @description Wire shape of the per-cluster health probe (mirrors ``HealthStatus``).
     */
    HealthCheckResult: {
      /**
       * Status
       * @enum {string}
       */
      status: 'green' | 'yellow' | 'red' | 'unreachable';
      /** Version */
      version?: string | null;
      /** Checked At */
      checked_at: string;
      /** Error */
      error?: string | null;
    };
    /**
     * HealthResponse
     * @description The /healthz response body. Same shape for HTTP 200 and 503.
     */
    HealthResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded';
      subsystems: components['schemas']['Subsystems'];
      /**
       * Openai Endpoint
       * @description Configured OPENAI_BASE_URL
       */
      openai_endpoint: string;
      openai_capabilities: components['schemas']['OpenAICapabilities'];
      /**
       * Version
       * @description Application version (relyloop_git_sha)
       */
      version: string;
      /**
       * Uptime Seconds
       * @description Seconds since the API process started
       */
      uptime_seconds: number;
    };
    /**
     * ImportJudgmentItem
     * @description One row in :class:`ImportJudgmentListRequest`.
     */
    ImportJudgmentItem: {
      /** Query Id */
      query_id: string;
      /** Doc Id */
      doc_id: string;
      /**
       * Rating
       * @enum {integer}
       */
      rating: 0 | 1 | 2 | 3;
      /** Notes */
      notes?: string | null;
    };
    /**
     * ImportJudgmentListRequest
     * @description Body for ``POST /api/v1/judgment-lists/import`` (Story 3.2).
     */
    ImportJudgmentListRequest: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Query Set Id */
      query_set_id: string;
      /** Cluster Id */
      cluster_id: string;
      /** Target */
      target: string;
      /** Rubric */
      rubric: string;
      /** Judgments */
      judgments: components['schemas']['ImportJudgmentItem'][];
    };
    /**
     * JudgmentListDetail
     * @description ``GET /api/v1/judgment-lists/{id}`` response.
     */
    JudgmentListDetail: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Query Set Id */
      query_set_id: string;
      /** Cluster Id */
      cluster_id: string;
      /** Target */
      target: string;
      /** Current Template Id */
      current_template_id: string | null;
      /** Rubric */
      rubric: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'generating' | 'complete' | 'failed';
      /** Failed Reason */
      failed_reason: string | null;
      /** Judgment Count */
      judgment_count: number;
      source_breakdown: components['schemas']['_SourceBreakdown'];
      /** Calibration */
      calibration: {
        [key: string]: unknown;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * JudgmentListJudgmentsResponse
     * @description ``GET /api/v1/judgment-lists/{id}/judgments`` response.
     */
    JudgmentListJudgmentsResponse: {
      /** Data */
      data: components['schemas']['JudgmentRow'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
    };
    /**
     * JudgmentListListResponse
     * @description ``GET /api/v1/judgment-lists`` response.
     */
    JudgmentListListResponse: {
      /** Data */
      data: components['schemas']['JudgmentListSummary'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
    };
    /**
     * JudgmentListSummary
     * @description List-view row on ``GET /api/v1/judgment-lists``.
     */
    JudgmentListSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Query Set Id */
      query_set_id: string;
      /** Cluster Id */
      cluster_id: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'generating' | 'complete' | 'failed';
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * JudgmentRow
     * @description ``GET /api/v1/judgment-lists/{id}/judgments`` row + PATCH response.
     */
    JudgmentRow: {
      /** Id */
      id: string;
      /** Judgment List Id */
      judgment_list_id: string;
      /** Query Id */
      query_id: string;
      /** Doc Id */
      doc_id: string;
      /**
       * Rating
       * @enum {integer}
       */
      rating: 0 | 1 | 2 | 3;
      /**
       * Source
       * @enum {string}
       */
      source: 'llm' | 'human' | 'click';
      /** Rater Ref */
      rater_ref: string | null;
      /** Confidence */
      confidence: number | null;
      /** Notes */
      notes: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ObjectiveSpec
     * @description Wire shape of ``studies.objective`` (write-side validated at create).
     *
     *     ``k`` is required for ``ndcg`` / ``precision`` / ``recall`` (per
     *     pytrec_eval semantics: those metrics are computed at a cutoff
     *     rank). ``map`` accepts ``k`` optionally; ``mrr`` / ``err`` ignore
     *     it. The model_validator enforces this so a malformed objective
     *     surfaces as 400 ``INVALID_SEARCH_SPACE`` / 422 ``VALIDATION_ERROR``
     *     at study-create time rather than failing later inside ``run_trial``
     *     when the worker computes the metric.
     */
    ObjectiveSpec: {
      /**
       * Metric
       * @enum {string}
       */
      metric: 'ndcg' | 'map' | 'precision' | 'recall' | 'mrr' | 'err';
      /** K */
      k?: (1 | 3 | 5 | 10 | 20 | 50 | 100) | null;
      /**
       * Direction
       * @default maximize
       * @enum {string}
       */
      direction: 'maximize' | 'minimize';
    };
    /**
     * OpenAICapabilities
     * @description Cached results of the OpenAI capability check (Story 3.3 populates Redis).
     */
    OpenAICapabilities: {
      /**
       * Chat
       * @description Chat completion probe result
       * @enum {string}
       */
      chat: 'ok' | 'fail' | 'untested';
      /**
       * Function Calling
       * @description Function-calling probe result (tool_choice=required)
       * @enum {string}
       */
      function_calling: 'ok' | 'fail' | 'untested';
      /**
       * Structured Output
       * @description JSON-schema response_format probe result
       * @enum {string}
       */
      structured_output: 'ok' | 'fail' | 'untested';
    };
    /**
     * OpenPrResponse
     * @description Body of ``POST /api/v1/proposals/{id}/open_pr`` (FR-1).
     *
     *     Returned with HTTP 202 on successful enqueue. Status is always
     *     ``'pending'`` at enqueue time; the worker flips it to ``'pr_opened'``
     *     after the PR is open.
     */
    OpenPrResponse: {
      /** Proposal Id */
      proposal_id: string;
      /**
       * Status
       * @constant
       */
      status: 'pending';
      /** Message */
      message: string;
    };
    /**
     * OverrideJudgmentRequest
     * @description Body for ``PATCH /api/v1/judgment-lists/{id}/judgments/{judgment_id}``.
     *
     *     ``rating`` is INTENTIONALLY unbounded at the Pydantic layer — spec §8.5
     *     requires out-of-range failures to surface as 400 ``INVALID_RATING`` (not
     *     Pydantic's default 422 ``VALIDATION_ERROR``). The handler validates the
     *     value manually and raises the domain code (per GPT-5.5 cycle 1 F4).
     */
    OverrideJudgmentRequest: {
      /** Rating */
      rating: number;
      /** Notes */
      notes?: string | null;
    };
    /**
     * ProposalDetail
     * @description Body of the proposal detail endpoints.
     *
     *     Used by ``GET /api/v1/proposals/{id}``, ``POST /api/v1/proposals``,
     *     and ``POST /api/v1/proposals/{id}/reject``.
     */
    ProposalDetail: {
      /** Id */
      id: string;
      /** Study Id */
      study_id: string | null;
      study_summary: components['schemas']['_StudySummary'] | null;
      /** Study Trial Id */
      study_trial_id: string | null;
      cluster: components['schemas']['_ClusterEmbed'];
      template: components['schemas']['_TemplateEmbed'];
      /** Config Diff */
      config_diff: {
        [key: string]: unknown;
      };
      /** Metric Delta */
      metric_delta: {
        [key: string]: unknown;
      } | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'pr_opened' | 'pr_merged' | 'rejected';
      /** Pr Url */
      pr_url: string | null;
      /** Pr State */
      pr_state: ('open' | 'closed' | 'merged') | null;
      /** Pr Merged At */
      pr_merged_at: string | null;
      /** Pr Open Error */
      pr_open_error: string | null;
      /** Rejected Reason */
      rejected_reason: string | null;
      digest: components['schemas']['_DigestEmbed'] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ProposalSummary
     * @description Row in the ``GET /api/v1/proposals`` list response.
     */
    ProposalSummary: {
      /** Id */
      id: string;
      /** Study Id */
      study_id: string | null;
      cluster: components['schemas']['_ClusterEmbed'];
      template: components['schemas']['_TemplateEmbed'];
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'pr_opened' | 'pr_merged' | 'rejected';
      /** Pr State */
      pr_state: ('open' | 'closed' | 'merged') | null;
      /** Pr Url */
      pr_url: string | null;
      /** Metric Delta */
      metric_delta: {
        [key: string]: unknown;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ProposalsListResponse
     * @description Body of ``GET /api/v1/proposals``.
     */
    ProposalsListResponse: {
      /** Data */
      data: components['schemas']['ProposalSummary'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
    };
    /**
     * QuerySetDetail
     * @description ``GET /api/v1/query-sets/{id}`` response.
     */
    QuerySetDetail: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Cluster Id */
      cluster_id: string;
      /** Query Count */
      query_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * QuerySetListResponse
     * @description ``GET /api/v1/query-sets`` response.
     */
    QuerySetListResponse: {
      /** Data */
      data: components['schemas']['QuerySetSummary'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
    };
    /**
     * QuerySetSummary
     * @description List-view shape; omits ``query_count`` to avoid N+1 counts at list time.
     */
    QuerySetSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Cluster Id */
      cluster_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * QueryTemplateDetail
     * @description ``GET /api/v1/query-templates/{id}`` response.
     */
    QueryTemplateDetail: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Engine Type
       * @enum {string}
       */
      engine_type: 'elasticsearch' | 'opensearch';
      /** Body */
      body: string;
      /** Declared Params */
      declared_params: {
        [key: string]: string;
      };
      /** Version */
      version: number;
      /** Parent Id */
      parent_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * QueryTemplateListResponse
     * @description ``GET /api/v1/query-templates`` response.
     */
    QueryTemplateListResponse: {
      /** Data */
      data: components['schemas']['QueryTemplateSummary'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
    };
    /**
     * QueryTemplateSummary
     * @description List-view shape; drops ``body`` + ``declared_params`` for brevity.
     */
    QueryTemplateSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Engine Type
       * @enum {string}
       */
      engine_type: 'elasticsearch' | 'opensearch';
      /** Version */
      version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * RejectProposalRequest
     * @description Body of ``POST /api/v1/proposals/{id}/reject`` (FR-4 / AC-5).
     */
    RejectProposalRequest: {
      /** Reason */
      reason?: string | null;
    };
    /**
     * RunQueryHit
     * @description One hit in the ``run_query`` response.
     */
    RunQueryHit: {
      /** Doc Id */
      doc_id: string;
      /** Score */
      score: number;
      /** Source */
      source?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * RunQueryRequest
     * @description ``POST /api/v1/clusters/{id}/run_query`` body.
     */
    RunQueryRequest: {
      /** Target */
      target: string;
      /** Query Dsl */
      query_dsl: {
        [key: string]: unknown;
      };
      /**
       * Top K
       * @default 10
       */
      top_k: number;
    };
    /**
     * RunQueryResponse
     * @description ``POST /api/v1/clusters/{id}/run_query`` response.
     */
    RunQueryResponse: {
      /** Hits */
      hits: components['schemas']['RunQueryHit'][];
    };
    /**
     * Schema
     * @description An index / collection's field schema.
     */
    Schema: {
      /** Name */
      name: string;
      /** Fields */
      fields: components['schemas']['FieldSpec'][];
    };
    /**
     * StudyConfigSpec
     * @description Wire shape of ``studies.config`` (write-side).
     *
     *     The model_validator below enforces that at least one stop condition is
     *     set — otherwise the study has no terminating condition (FR-4).
     *     ``parallelism`` / ``trial_timeout_s`` are optional; when absent the
     *     worker reads ``Settings.studies_default_parallelism`` /
     *     ``studies_default_timeout_s`` at job time. The API layer does NOT
     *     materialize these fields into the stored row — see Story 1.5 +
     *     Story 3.3's ``config.model_dump(exclude_none=True, exclude_unset=True)``
     *     contract.
     */
    StudyConfigSpec: {
      /** Max Trials */
      max_trials?: number | null;
      /** Time Budget Min */
      time_budget_min?: number | null;
      /** Parallelism */
      parallelism?: number | null;
      /** Trial Timeout S */
      trial_timeout_s?: number | null;
      /** Sampler */
      sampler?: ('tpe' | 'random') | null;
      /** Pruner */
      pruner?: ('median' | 'none') | null;
      /** Seed */
      seed?: number | null;
      /** Secondary Metrics */
      secondary_metrics?: string[] | null;
    };
    /**
     * StudyDetail
     * @description ``GET /api/v1/studies/{id}`` response + ``POST/cancel`` response.
     */
    StudyDetail: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Cluster Id */
      cluster_id: string;
      /** Target */
      target: string;
      /** Template Id */
      template_id: string;
      /** Query Set Id */
      query_set_id: string;
      /** Judgment List Id */
      judgment_list_id: string;
      /** Search Space */
      search_space: {
        [key: string]: unknown;
      };
      /** Objective */
      objective: {
        [key: string]: unknown;
      };
      /** Config */
      config: {
        [key: string]: unknown;
      };
      /**
       * Status
       * @enum {string}
       */
      status: 'queued' | 'running' | 'completed' | 'cancelled' | 'failed';
      /** Failed Reason */
      failed_reason: string | null;
      /** Optuna Study Name */
      optuna_study_name: string;
      /** Parent Study Id */
      parent_study_id: string | null;
      /** Baseline Metric */
      baseline_metric: number | null;
      /** Best Metric */
      best_metric: number | null;
      /** Best Trial Id */
      best_trial_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Started At */
      started_at: string | null;
      /** Completed At */
      completed_at: string | null;
      trials_summary: components['schemas']['TrialsSummaryShape'];
    };
    /**
     * StudyListResponse
     * @description ``GET /api/v1/studies`` response.
     */
    StudyListResponse: {
      /** Data */
      data: components['schemas']['StudySummary'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
    };
    /**
     * StudySummary
     * @description List-view shape.
     */
    StudySummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Cluster Id */
      cluster_id: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'queued' | 'running' | 'completed' | 'cancelled' | 'failed';
      /** Best Metric */
      best_metric: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Completed At */
      completed_at: string | null;
    };
    /**
     * Subsystems
     * @description Per-subsystem reachability/configuration state. Wire values per spec §7.4.
     */
    Subsystems: {
      /**
       * Db
       * @description Postgres reachability
       * @enum {string}
       */
      db: 'ok' | 'down';
      /**
       * Redis
       * @description Redis reachability
       * @enum {string}
       */
      redis: 'ok' | 'down';
      /**
       * Openai
       * @description OpenAI key + capability state. 'incapable' added per FR-2 vs. spec §7.4 enum table — see implementation_plan.md §13 Review log.
       * @enum {string}
       */
      openai: 'configured' | 'missing_key' | 'incapable';
      /**
       * Elasticsearch
       * @description Local Elasticsearch container reachability
       * @enum {string}
       */
      elasticsearch: 'reachable' | 'unreachable';
      /**
       * Opensearch
       * @description Local OpenSearch container reachability
       * @enum {string}
       */
      opensearch: 'reachable' | 'unreachable';
      /** @description Aggregate health of user-registered clusters (infra_adapter_elastic Story 3.5 / spec §2). registered=0 → all-zero counts; informational only — does NOT trigger overall `degraded`. */
      elasticsearch_clusters: components['schemas']['ClusterAggregateHealth'];
    };
    /**
     * TrialDetail
     * @description ``GET /api/v1/studies/{id}/trials`` response row.
     */
    TrialDetail: {
      /** Id */
      id: string;
      /** Study Id */
      study_id: string;
      /** Optuna Trial Number */
      optuna_trial_number: number;
      /** Params */
      params: {
        [key: string]: unknown;
      };
      /** Primary Metric */
      primary_metric: number | null;
      /** Metrics */
      metrics: {
        [key: string]: unknown;
      };
      /** Duration Ms */
      duration_ms: number | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'complete' | 'failed' | 'pruned';
      /** Error */
      error: string | null;
      /** Started At */
      started_at: string | null;
      /** Ended At */
      ended_at: string | null;
    };
    /**
     * TrialListResponse
     * @description ``GET /api/v1/studies/{id}/trials`` response.
     */
    TrialListResponse: {
      /** Data */
      data: components['schemas']['TrialDetail'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
    };
    /**
     * TrialsSummaryShape
     * @description The ``trials_summary`` field embedded in :class:`StudyDetail`.
     */
    TrialsSummaryShape: {
      /** Total */
      total: number;
      /** Complete */
      complete: number;
      /** Failed */
      failed: number;
      /** Pruned */
      pruned: number;
      /** Best Primary Metric */
      best_primary_metric: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * _ClusterEmbed
     * @description Inline cluster summary on proposal responses.
     */
    _ClusterEmbed: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Engine Type */
      engine_type: string;
      /** Environment */
      environment?: string | null;
    };
    /**
     * _DigestEmbed
     * @description Inline digest summary on the proposal-detail response.
     */
    _DigestEmbed: {
      /** Id */
      id: string;
      /** Narrative */
      narrative: string;
      /** Parameter Importance */
      parameter_importance: {
        [key: string]: number;
      };
      /** Recommended Config */
      recommended_config: {
        [key: string]: unknown;
      };
      /** Suggested Followups */
      suggested_followups: string[];
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
    };
    /**
     * _SourceBreakdown
     * @description Source-breakdown sub-shape on :class:`JudgmentListDetail`.
     *
     *     Per spec FR-6 the response names only ``llm`` and ``human`` (GPT-5.5
     *     cycle 1 F6). Reserved ``click`` rows fold into ``human`` per the cycle 2
     *     F6 invariant ``llm + human == judgment_count``.
     */
    _SourceBreakdown: {
      /** Llm */
      llm: number;
      /** Human */
      human: number;
    };
    /**
     * _StudySummary
     * @description Inline study summary on the proposal-detail response.
     */
    _StudySummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** Best Metric */
      best_metric: number | null;
      /** Best Trial Id */
      best_trial_id: string | null;
      /** Query Set */
      query_set: {
        [key: string]: unknown;
      };
      /** Judgment List */
      judgment_list: {
        [key: string]: unknown;
      };
    };
    /**
     * _TemplateEmbed
     * @description Inline template summary on proposal responses.
     */
    _TemplateEmbed: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Version */
      version: number;
      /** Engine Type */
      engine_type?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
      /** @description One or more required subsystems is down */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  list_clusters_api_v1_clusters_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
        since?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClusterListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_cluster_api_v1_clusters_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateClusterRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClusterDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_cluster_detail_api_v1_clusters__cluster_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cluster_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClusterDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_cluster_api_v1_clusters__cluster_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cluster_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_cluster_schema_api_v1_clusters__cluster_id__schema_get: {
    parameters: {
      query: {
        target: string;
      };
      header?: never;
      path: {
        cluster_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Schema'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  run_query_api_v1_clusters__cluster_id__run_query_post: {
    parameters: {
      query?: {
        timeout_s?: number;
      };
      header?: never;
      path: {
        cluster_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RunQueryRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunQueryResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_query_templates_api_v1_query_templates_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
        since?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QueryTemplateListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_query_template_api_v1_query_templates_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateQueryTemplateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QueryTemplateDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_query_template_detail_api_v1_query_templates__template_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        template_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QueryTemplateDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_query_sets_api_v1_query_sets_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
        since?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuerySetListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_query_set_api_v1_query_sets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateQuerySetRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuerySetDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_query_set_detail_api_v1_query_sets__query_set_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        query_set_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuerySetDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  bulk_add_queries_api_v1_query_sets__query_set_id__queries_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        query_set_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BulkQueriesResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_studies_api_v1_studies_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
        since?: string | null;
        status?: ('queued' | 'running' | 'completed' | 'cancelled' | 'failed') | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StudyListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_study_api_v1_studies_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateStudyRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StudyDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_study_detail_api_v1_studies__study_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        study_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StudyDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  cancel_study_api_v1_studies__study_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        study_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StudyDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_study_trials_api_v1_studies__study_id__trials_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
        since?: string | null;
        sort?: string;
      };
      header?: never;
      path: {
        study_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrialListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generate_judgments_api_v1_judgments_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateJudgmentListGenerateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenerateJudgmentsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  import_judgment_list_api_v1_judgment_lists_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ImportJudgmentListRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JudgmentListDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_judgment_lists_endpoint_api_v1_judgment_lists_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JudgmentListListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_judgment_list_endpoint_api_v1_judgment_lists__judgment_list_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judgment_list_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JudgmentListDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_judgments_endpoint_api_v1_judgment_lists__judgment_list_id__judgments_get: {
    parameters: {
      query?: {
        source?: ('llm' | 'human') | null;
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path: {
        judgment_list_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JudgmentListJudgmentsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  override_judgment_api_v1_judgment_lists__judgment_list_id__judgments__judgment_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judgment_list_id: string;
        judgment_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OverrideJudgmentRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JudgmentRow'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  calibrate_judgment_list_api_v1_judgment_lists__judgment_list_id__calibration_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        judgment_list_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CalibrationSamplesRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CalibrationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_study_digest_api_v1_studies__study_id__digest_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        study_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DigestResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_proposals_endpoint_api_v1_proposals_get: {
    parameters: {
      query?: {
        status?: ('pending' | 'pr_opened' | 'pr_merged' | 'rejected') | null;
        cluster_id?: string | null;
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalsListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_manual_proposal_api_v1_proposals_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProposalRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_proposal_endpoint_api_v1_proposals__proposal_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        proposal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reject_proposal_endpoint_api_v1_proposals__proposal_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        proposal_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RejectProposalRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  open_pr_endpoint_api_v1_proposals__proposal_id__open_pr_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        proposal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenPrResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_config_repos_endpoint_api_v1_config_repos_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfigReposListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_config_repo_endpoint_api_v1_config_repos_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateConfigRepoRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfigRepoDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_config_repo_endpoint_api_v1_config_repos__config_repo_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        config_repo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfigRepoDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
