# SPDX-FileCopyrightText: 2026 soundminds.ai
#
# SPDX-License-Identifier: Apache-2.0

"""Generate the relyloop.com Guides pages from the in-repo source assets.

Single source of truth:
  - ``ui/public/guides/<NN_slug>/`` — 10 walkthrough decks (metadata.json +
    numbered PNGs + walkthrough.webm [+ walkthrough.mp4 when transcoded]).
  - ``docs/08_guides/*.md`` — 4 long-form guides.

This generator mirrors those into the MkDocs Material site under
``website/docs/``, emitting:
  - ``website/docs/guides/walkthroughs/<slug>.md`` (one per deck) + index.md
  - ``website/docs/guides/in-depth/<basename>`` (one per long-form) + index.md
  - ``website/docs/assets/guides/<slug>/*`` (copied PNG + WebM [+ MP4])
  - a managed ``Guides:`` nav fragment inside ``website/mkdocs.yml`` (between
    BEGIN/END sentinels — the rest of the nav stays hand-written).

It is STDLIB-ONLY (no PyYAML, no third-party imports) so it runs on the
Python-only GitHub-Pages deploy runner and at PR time in the freshness gate
without any extra ``pip install``. Mirrors the single-direction-mirror +
prune discipline of ``ui/scripts/copy-docs.mjs``.

Run:
    python website/scripts/build_guides.py              # generate (default)
    python website/scripts/build_guides.py --transcode  # also (re)produce MP4s via ffmpeg

Importing this module does NOT trigger generation — the bottom-of-file
``if __name__ == "__main__":`` entrypoint gates the run, so the pytest at
``backend/tests/unit/scripts/test_build_guides.py`` can import and exercise
the individual functions against tmp fixtures.

The generated ``.md`` files and the three destination directories
(``website/docs/guides/walkthroughs/``, ``website/docs/guides/in-depth/``,
``website/docs/assets/guides/``) are GENERATOR-OWNED — do not hand-edit;
re-running prunes anything the generator didn't emit.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit, urlunsplit

# --------------------------------------------------------------------------- #
# Paths (resolved relative to this file — NOT via `git rev-parse`, to stay     #
# hermetic). website/scripts/build_guides.py -> parents[2] == repo root.       #
# --------------------------------------------------------------------------- #
REPO_ROOT = Path(__file__).resolve().parents[2]
GUIDES_SRC = REPO_ROOT / "ui" / "public" / "guides"
DOCS_SRC = REPO_ROOT / "docs" / "08_guides"
WEBSITE = REPO_ROOT / "website"
WALKTHROUGHS_OUT = WEBSITE / "docs" / "guides" / "walkthroughs"
INDEPTH_OUT = WEBSITE / "docs" / "guides" / "in-depth"
ASSETS_OUT = WEBSITE / "docs" / "assets" / "guides"
MKDOCS_YML = WEBSITE / "mkdocs.yml"

# The 4 long-form guides, hard-coded (mirrors copy-docs.mjs's explicit DOCS
# array). A NEW guide in docs/08_guides/ does NOT auto-publish — add it here.
# Order is the display order on the In-depth index + nav.
LONG_FORM_GUIDES: tuple[str, ...] = (
    "tutorial-first-study.md",
    "quick-tour.md",
    "workflows-overview.md",
    "llm-endpoint-setup.md",
)
# Human-facing nav/index labels for the long-form guides (static — not
# data-driven from a free-text field, so the nav splice can hard-code them).
LONG_FORM_TITLES: dict[str, str] = {
    "tutorial-first-study.md": "Tutorial — first study",
    "quick-tour.md": "Quick tour",
    "workflows-overview.md": "Workflows overview",
    "llm-endpoint-setup.md": "LLM endpoint setup",
}

SLUG_RE = re.compile(r"^[a-zA-Z0-9_-]+$")
# Declared screenshot filenames must be plain basenames (no path separators,
# no `..`, no leading `/`) ending in .png — they come from metadata.json, which
# is contributor-editable, so this is the path-traversal guard for the copy +
# emit steps. (The video filename is locked separately to "walkthrough.webm".)
SCREENSHOT_NAME_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9._-]*\.png$")
SCREENSHOT_PREFIX_RE = re.compile(r"^(\d+)")
LOCKED_VIDEO_NAME = "walkthrough.webm"
LOCKED_VIDEO_MP4 = "walkthrough.mp4"

GENERATED_HEADER_FMT = (
    "<!-- GENERATED by website/scripts/build_guides.py from {source} — DO NOT EDIT. -->"
)

GITHUB_BLOB = "https://github.com/SoundMindsAI/relyloop/blob/main/"
GITHUB_TREE = "https://github.com/SoundMindsAI/relyloop/tree/main/"

# Inline-Markdown links ONLY: [text](url). The negative lookbehind excludes
# image links ![alt](url). Reference-style, HTML <a>, and autolinks are NOT
# matched here (detect_unsupported_relative_links flags any that point at a
# relative repo path).
#
# The text group allows ONE level of nested brackets so link text like
# ``[`/templates/[id]`](url)`` (a Next.js dynamic-route path in backticks)
# matches. re.DOTALL lets the text span a line break — the tutorial has a
# ``[smoke\ntest](url)`` link wrapped across two source lines.
INLINE_LINK_RE = re.compile(
    r"(?<!\!)\[(?P<text>(?:[^\[\]]|\[[^\[\]]*\])*)\]\((?P<url>[^)]+)\)",
    re.DOTALL,
)
PRESENTER_COMMENT_RE = re.compile(r"<!--\s*presenter:.*?-->", re.DOTALL)


# --------------------------------------------------------------------------- #
# Errors                                                                       #
# --------------------------------------------------------------------------- #
class LinkRewriteError(ValueError):
    """Raised by rewrite_link with the offending target + reason; the caller
    (port_long_form_guide) knows the source file + line and re-raises a
    SystemExit with the full ``file:line ... target`` diagnostic."""

    def __init__(self, target: str, reason: str) -> None:
        self.target = target
        self.reason = reason
        super().__init__(f"{reason}: {target!r}")


# --------------------------------------------------------------------------- #
# Deck discovery                                                               #
# --------------------------------------------------------------------------- #
def _screenshot_sort_key(name: str) -> tuple[int, str]:
    m = SCREENSHOT_PREFIX_RE.match(name)
    return (int(m.group(1)) if m else 1_000_000, name)


def discover_decks(guides_src: Path) -> list[dict[str, Any]]:
    """Return the deck records sorted by slug (lexicographic).

    Each record: {slug, title, description, estimated_time, tags,
    screenshots:[{file,caption}], video}. A deck whose metadata.json is
    absent is skipped with a WARN (partial working tree is not a hard fail —
    the freshness gate catches the drift). Raises SystemExit(1) on an invalid
    slug or a metadata.json whose ``video`` is not the locked basename.

    The single sort point: every downstream consumer (index, nav) inherits a
    deterministic order regardless of filesystem iteration order.
    """
    decks: list[dict[str, Any]] = []
    if not guides_src.is_dir():
        return decks
    for child in sorted(guides_src.iterdir(), key=lambda p: p.name):
        if not child.is_dir():
            continue
        slug = child.name
        meta_path = child / "metadata.json"
        if not meta_path.is_file():
            print(f"WARN: deck={slug} missing metadata.json — skipping", file=sys.stderr)
            continue
        if not SLUG_RE.match(slug):
            raise SystemExit(
                f"ERROR: deck slug {slug!r} is not a safe identifier (must match {SLUG_RE.pattern})"
            )
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise SystemExit(f"ERROR: deck={slug} metadata.json is not valid JSON: {exc}") from exc
        for key in ("title", "screenshots"):
            if key not in meta:
                raise SystemExit(f"ERROR: deck={slug} metadata.json missing required key {key!r}")
        video = meta.get("video")
        if video is not None and video != LOCKED_VIDEO_NAME:
            raise SystemExit(
                f'ERROR: deck={slug} metadata.json.video must be "{LOCKED_VIDEO_NAME}", '
                f"got {video!r}"
            )
        screenshots = sorted(
            meta.get("screenshots", []),
            key=lambda s: _screenshot_sort_key(s.get("file", "")),
        )
        # Path-traversal guard: declared screenshot filenames must be plain
        # .png basenames (metadata.json is contributor-editable).
        for shot in screenshots:
            fname = shot.get("file", "")
            if not SCREENSHOT_NAME_RE.match(fname):
                raise SystemExit(
                    f"ERROR: deck={slug} screenshot file {fname!r} is not a safe "
                    f".png basename (must match {SCREENSHOT_NAME_RE.pattern})"
                )
        decks.append(
            {
                "slug": slug,
                "title": meta["title"],
                "description": meta.get("description", ""),
                "estimated_time": meta.get("estimated_time", ""),
                "tags": meta.get("tags", []),
                "screenshots": screenshots,
                "video": video,
            }
        )
    return decks


# --------------------------------------------------------------------------- #
# Asset copy                                                                   #
# --------------------------------------------------------------------------- #
def copy_deck_assets(deck: dict[str, Any], src_dir: Path, dst_dir: Path) -> set[str]:
    """Copy the deck's declared PNGs + walkthrough.webm (+ .mp4 if present)
    into dst_dir. Returns the set of copied basenames (used by main() to
    derive has_webm/has_mp4 for the video block — the copied set is the single
    source of truth, NOT a re-stat of dst_dir)."""
    dst_dir.mkdir(parents=True, exist_ok=True)
    copied: set[str] = set()
    for shot in deck["screenshots"]:
        fname = shot.get("file")
        if not fname:
            continue
        src = src_dir / fname
        if not src.is_file():
            print(
                f"WARN: deck={deck['slug']} missing screenshot={fname} — skipping row",
                file=sys.stderr,
            )
            continue
        shutil.copy2(src, dst_dir / fname)
        copied.add(fname)
    for video_name in (LOCKED_VIDEO_NAME, LOCKED_VIDEO_MP4):
        src = src_dir / video_name
        if src.is_file():
            shutil.copy2(src, dst_dir / video_name)
            copied.add(video_name)
    return copied


# --------------------------------------------------------------------------- #
# Markdown emit                                                                #
# --------------------------------------------------------------------------- #
def _first_words(text: str, n: int = 8) -> str:
    words = text.strip().split()
    head = " ".join(words[:n])
    return head + ("…" if len(words) > n else "")


def emit_deck_page(deck: dict[str, Any], has_webm: bool, has_mp4: bool, copied: set[str]) -> str:
    """Return the full markdown body for walkthroughs/<slug>.md.

    has_webm/has_mp4/copied are passed by main() (derived from
    copy_deck_assets's returned set) — emit_deck_page does NOT re-stat the dest
    tree, so a stale dest file that the current run will prune cannot influence
    the markup. A screenshot whose source was missing (not in ``copied``) is
    skipped so the page never references an asset that was not copied.
    """
    slug = deck["slug"]
    lines: list[str] = [
        GENERATED_HEADER_FMT.format(source=f"ui/public/guides/{slug}/"),
        "",
        f"# {deck['title']}",
        "",
    ]
    admon: list[str] = []
    if deck["estimated_time"]:
        admon.append(f"**Estimated time:** {deck['estimated_time']}")
    if deck["tags"]:
        admon.append(f"**Tags:** {', '.join(deck['tags'])}")
    if admon:
        lines.append('!!! info "About this walkthrough"')
        for a in admon:
            lines.append(f"    {a}")
        lines.append("")
    if deck["description"]:
        lines.append(deck["description"])
        lines.append("")
    video = build_video_block(slug, has_webm, has_mp4)
    if video:
        lines.append(video)
        lines.append("")
    step = 0
    for shot in deck["screenshots"]:
        fname = shot.get("file")
        caption = shot.get("caption", "")
        if not fname or fname not in copied:
            # Skip the row when the source screenshot was missing (and thus not
            # copied) — never emit a Markdown link to an asset that isn't there.
            continue
        step += 1
        heading = _first_words(caption) or fname
        lines.append(f"## Step {step} — {heading}")
        lines.append("")
        lines.append(f"![{caption}](../../assets/guides/{slug}/{fname})")
        lines.append("")
    lines.append("[← Back to walkthroughs](index.md)")
    lines.append("")
    return "\n".join(lines)


def emit_walkthroughs_index(
    decks: list[dict[str, Any]], copied_by_slug: dict[str, set[str]] | None = None
) -> str:
    """Return walkthroughs/index.md — a Material card grid, one card per deck,
    in lexicographic slug order (decks already sorted by discover_decks).

    The card thumbnail is the first screenshot whose source was actually copied
    (per ``copied_by_slug``) — never a missing asset. When ``copied_by_slug`` is
    None (callers that don't track copies, e.g. some tests) it falls back to the
    first declared screenshot.
    """
    lines: list[str] = [
        GENERATED_HEADER_FMT.format(source="ui/public/guides/*/metadata.json"),
        "",
        "# Walkthroughs",
        "",
        "Short, click-through walkthroughs of every RelyLoop workflow — each a "
        "sequence of annotated screenshots with a slow-motion video. Start with "
        "registering a cluster and follow the loop all the way to a merged "
        "configuration PR.",
        "",
        '<div class="grid cards" markdown>',
        "",
    ]
    for deck in decks:
        slug = deck["slug"]
        # Pick the first screenshot whose source was copied — never reference a
        # missing asset (the index would otherwise ship a broken thumbnail and
        # the freshness gate, which excludes nothing here, would still pass).
        copied = copied_by_slug.get(slug) if copied_by_slug is not None else None
        thumb = ""
        for shot in deck["screenshots"]:
            fname = shot.get("file", "")
            if fname and (copied is None or fname in copied):
                thumb = fname
                break
        card: list[str] = [f"-   ### [{deck['title']}]({slug}.md)", ""]
        if thumb:
            # {.glightbox-skip} so clicking the thumbnail navigates to the deck
            # (the <a> wrapper wins) rather than opening a lightbox overlay.
            card.append(
                f"    [![{deck['title']}](../../assets/guides/{slug}/{thumb})"
                f"{{.glightbox-skip}}]({slug}.md)"
            )
            card.append("")
        meta_bits = []
        if deck["estimated_time"]:
            meta_bits.append(f"⏱ {deck['estimated_time']}")
        if deck["tags"]:
            meta_bits.append(f"🏷 {deck['tags'][0]}")
        if meta_bits:
            card.append(f"    {' · '.join(meta_bits)}")
            card.append("")
        card.append(f"    [Open walkthrough →]({slug}.md)")
        card.append("")
        lines.extend(card)
    lines.append("</div>")
    lines.append("")
    return "\n".join(lines)


def emit_indepth_index(guides: list[str]) -> str:
    """Return in-depth/index.md — a card grid for the long-form guides."""
    lines: list[str] = [
        GENERATED_HEADER_FMT.format(source="docs/08_guides/*.md"),
        "",
        "# In-depth guides",
        "",
        "Long-form, reference-shaped guides for operators who want the full "
        "picture — the 30-minute end-to-end tutorial, the 10-minute value tour, "
        "the workflow inventory, and the LLM endpoint setup matrix.",
        "",
        '<div class="grid cards" markdown>',
        "",
    ]
    for basename in guides:
        title = LONG_FORM_TITLES.get(basename, basename)
        slug = basename[:-3] if basename.endswith(".md") else basename
        lines.append(f"-   ### [{title}]({slug}.md)")
        lines.append("")
        lines.append(f"    [Open guide →]({slug}.md)")
        lines.append("")
    lines.append("</div>")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Video block (Story 1.3 fills this; Story 1.1 ships the placeholder contract) #
# --------------------------------------------------------------------------- #
def build_video_block(slug: str, has_webm: bool, has_mp4: bool) -> str:
    """Return the mobile-safe <video> block + a sibling download link, or ""
    when has_webm is False (no source WebM -> no video block per FR-3).

    MP4 <source> is listed FIRST (iff has_mp4) so iOS Safari picks it; the WebM
    <source> is always present (since has_webm); the download link is a SIBLING
    element below the <video> (NOT nested) so it stays visible on an iOS Safari
    that supports <video> but cannot decode any listed source.
    """
    if not has_webm:
        return ""
    base = f"../../assets/guides/{slug}"
    sources: list[str] = []
    if has_mp4:
        sources.append(f'  <source src="{base}/walkthrough.mp4" type="video/mp4">')
    sources.append(f'  <source src="{base}/walkthrough.webm" type="video/webm">')
    block = [
        '<video controls playsinline preload="metadata" class="walkthrough-video">',
        *sources,
        "  <p>Your browser cannot play the embedded video.</p>",
        "</video>",
        f'<p class="walkthrough-video-download">Trouble playing? '
        f'<a href="{base}/walkthrough.webm">Download the walkthrough video</a>.</p>',
    ]
    return "\n".join(block)


# --------------------------------------------------------------------------- #
# Long-form porting + link rewriting (Story 1.2)                               #
# --------------------------------------------------------------------------- #
def _is_relative_target(scheme: str, netloc: str) -> bool:
    """A target is relative iff it has no scheme and no netloc. This is the
    correct discriminator — ``mailto:x@y`` has scheme ``mailto`` (absolute),
    so it never trips the unsupported-relative-link check."""
    return scheme == "" and netloc == ""


def rewrite_link(url: str, repo_root: Path) -> str:
    """Rewrite a single inline-Markdown link URL per the FR-2 rules.

    Rule order (checks on the PARSED url, path-only rules reattach query+frag):
      1. scheme != ""           -> passthrough (https, http, mailto, tel, data)
      2. bare in-page anchor    -> passthrough (#anchor)
      3. intra-list link        -> strip ./, keep as in-site sibling basename
      4. off-site repo-relative -> normalize vs docs/08_guides/, assert exists,
                                   emit blob (file) / tree (dir) GitHub URL
    Raises LinkRewriteError(target, reason) on anything else (the caller adds
    file:line). reason is one of: "unmapped", "unresolved", "repo-escape".
    """
    scheme, netloc, path, query, fragment = urlsplit(url)

    # Rule 1: absolute URL (any scheme) — passthrough.
    if scheme != "":
        return url
    # Rule 2: bare in-page anchor — passthrough.
    if netloc == "" and path == "" and fragment != "":
        return url

    long_form = set(LONG_FORM_GUIDES)

    # Rule 3: intra-list link (optionally ./-prefixed).
    candidate = path[2:] if path.startswith("./") else path
    if candidate in long_form:
        return urlunsplit(("", "", candidate, query, fragment))

    # Rule 4: off-site repo-relative link.
    if path.startswith("../"):
        # Normalize against the source file's docs/08_guides/ location.
        base = repo_root / "docs" / "08_guides"
        resolved = (base / path).resolve()
        try:
            rel = resolved.relative_to(repo_root.resolve())
        except ValueError as exc:
            raise LinkRewriteError(url, "repo-escape") from exc
        if not resolved.exists():
            raise LinkRewriteError(url, "unresolved")
        rel_str = rel.as_posix()
        if resolved.is_dir() or path.endswith("/"):
            new_path = GITHUB_TREE + rel_str + ("/" if not rel_str.endswith("/") else "")
        else:
            new_path = GITHUB_BLOB + rel_str
        # new_path is a full absolute URL; reattach query+fragment by hand
        # (urlunsplit on an already-absolute string would double-encode).
        suffix = ""
        if query:
            suffix += f"?{query}"
        if fragment:
            suffix += f"#{fragment}"
        return new_path + suffix

    # Anything else relative (bare basename not in the long-form set, etc.).
    raise LinkRewriteError(url, "unmapped")


def detect_unsupported_relative_links(text: str, source_rel: str) -> None:
    """Scan for link syntaxes the rewriter does NOT handle (image links,
    reference-style, HTML <a href>, autolinks) whose target is a relative repo
    path. Raise SystemExit(1) with file:line so a future source guide that adds
    one surfaces the gap rather than silently mis-handling it."""
    patterns = [
        (re.compile(r"!\[[^\]]*\]\((?P<url>[^)]+)\)"), "image link"),
        (re.compile(r"^\s*\[[^\]]+\]:\s*(?P<url>\S+)", re.MULTILINE), "reference-style link"),
        # Both quote styles for HTML href.
        (
            re.compile(r"""<a\s+[^>]*href=(?P<q>["'])(?P<url>.*?)(?P=q)""", re.IGNORECASE),
            "HTML <a> link",
        ),
    ]
    for line_no, line in enumerate(text.splitlines(), start=1):
        for regex, label in patterns:
            for m in regex.finditer(line):
                target = m.group("url")
                scheme, netloc, _, _, _ = urlsplit(target)
                if _is_relative_target(scheme, netloc) and (
                    target.startswith("./")
                    or target.startswith("../")
                    or (not target.startswith("#") and "/" not in target.split("?")[0][:1])
                ):
                    # Only flag ./, ../ relative paths (bare in-page anchors and
                    # plain words are not repo links).
                    if target.startswith("./") or target.startswith("../"):
                        raise SystemExit(
                            f"ERROR: {source_rel}:{line_no} unsupported {label} syntax "
                            f"pointing at a relative repo path {target!r} — the rewriter "
                            f"only handles inline [text](url) links"
                        )


def port_long_form_guide(src: Path, repo_root: Path) -> str:
    """Read a long-form guide, strip presenter comments, rewrite every inline
    link, and prepend the GENERATED header. Raises SystemExit(1) on a missing
    source (the 4 guides are a fixed set — a missing one is a real error, and
    fail-loud here prevents a stale generated page surviving a source deletion
    the freshness gate can't see), or on an unmapped/unresolved link."""
    rel = src.relative_to(repo_root).as_posix()
    if not src.is_file():
        raise SystemExit(f"ERROR: long-form guide source missing: {rel}")
    text = PRESENTER_COMMENT_RE.sub("", src.read_text(encoding="utf-8"))
    detect_unsupported_relative_links(text, rel)

    # Process the WHOLE text (not line-by-line) so a link wrapped across a line
    # break — e.g. the tutorial's `[smoke\ntest](url)` — still matches. The
    # 1-based line number for diagnostics is derived from the match offset.
    def _replace(m: re.Match[str]) -> str:
        url = m.group("url")
        try:
            new_url = rewrite_link(url, repo_root)
        except LinkRewriteError as err:
            line_no = text.count("\n", 0, m.start()) + 1
            reason = {
                "unresolved": f'unresolved repo link "{err.target}" (not found in tree)',
                "repo-escape": f'repo-escaping link "{err.target}"',
                "unmapped": f'unmapped link rewrite for "{err.target}"',
            }[err.reason]
            raise SystemExit(f"ERROR: {rel}:{line_no} {reason}") from err
        return f"[{m.group('text')}]({new_url})"

    body = INLINE_LINK_RE.sub(_replace, text)
    header = GENERATED_HEADER_FMT.format(source=rel)
    # Normalize trailing whitespace to a single newline — stripping presenter
    # comments can leave trailing blank lines that end-of-file-fixer would
    # otherwise rewrite, making the generator fight the pre-commit hook (and
    # the freshness gate, which runs this generator).
    return header + "\n\n" + body.rstrip() + "\n"


# --------------------------------------------------------------------------- #
# Pruning (Story 1.4)                                                          #
# --------------------------------------------------------------------------- #
def prune_dir(directory: Path, expected: set[str]) -> list[str]:
    """Delete any immediate child of ``directory`` whose name is not in
    ``expected``. Recurses into expected-subdir pruning only via the caller
    (prune_all). Returns the relative paths pruned."""
    pruned: list[str] = []
    if not directory.is_dir():
        return pruned
    for child in sorted(directory.iterdir(), key=lambda p: p.name):
        if child.name not in expected:
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
            pruned.append(child.name)
    return pruned


def prune_all(decks: list[dict[str, Any]], copied_by_slug: dict[str, set[str]]) -> list[str]:
    """Prune the three generator-owned dirs to exactly the regenerated set.

    walkthroughs/: {index.md} ∪ {<slug>.md}
    in-depth/:     {index.md} ∪ {<basename> in LONG_FORM_GUIDES}
    assets/guides/<slug>/: the copied basenames for that deck
    Removes the asset dir of a deck no longer present.
    """
    pruned: list[str] = []
    wt_expected = {"index.md"} | {f"{d['slug']}.md" for d in decks}
    pruned += [f"walkthroughs/{p}" for p in prune_dir(WALKTHROUGHS_OUT, wt_expected)]

    indepth_expected = {"index.md"} | set(LONG_FORM_GUIDES)
    pruned += [f"in-depth/{p}" for p in prune_dir(INDEPTH_OUT, indepth_expected)]

    deck_slugs = {d["slug"] for d in decks}
    pruned += [f"assets/guides/{p}" for p in prune_dir(ASSETS_OUT, deck_slugs)]
    for deck in decks:
        slug = deck["slug"]
        expected = copied_by_slug.get(slug, set())
        pruned += [f"assets/guides/{slug}/{p}" for p in prune_dir(ASSETS_OUT / slug, expected)]
    return pruned


# --------------------------------------------------------------------------- #
# Managed nav fragment (Story 1.5)                                             #
# --------------------------------------------------------------------------- #
NAV_BEGIN = "  # >>> GENERATED Guides nav — DO NOT EDIT"
NAV_END = "  # <<< END GENERATED Guides nav"
ANCHOR_LINE = "  - API Reference: api/index.md"


def yaml_single_quote(label: str) -> str:
    """Encode a label as a YAML 1.2 single-quoted scalar (stdlib-only — no
    PyYAML). Internal single quotes are doubled per the spec."""
    return "'" + label.replace("'", "''") + "'"


def render_nav_fragment(decks: list[dict[str, Any]]) -> str:
    """Render the managed ``Guides:`` nav block (between the BEGIN/END markers,
    exclusive). Labels are single-quoted; decks are already slug-sorted."""
    lines = [
        "  - Guides:",
        "      - Walkthroughs:",
        f"          - {yaml_single_quote('Overview')}: guides/walkthroughs/index.md",
    ]
    for deck in decks:
        label = yaml_single_quote(deck["title"])
        lines.append(f"          - {label}: guides/walkthroughs/{deck['slug']}.md")
    lines.append("      - In-depth:")
    lines.append(f"          - {yaml_single_quote('Overview')}: guides/in-depth/index.md")
    for basename in LONG_FORM_GUIDES:
        title = LONG_FORM_TITLES.get(basename, basename)
        slug = basename[:-3] if basename.endswith(".md") else basename
        lines.append(f"          - {yaml_single_quote(title)}: guides/in-depth/{slug}.md")
    return "\n".join(lines)


def validate_mkdocs_anchor(text: str) -> None:
    """Validate mkdocs.yml shape before editing. Raises SystemExit(1) on:
    a partial (only one) marker; markers in the wrong order; not-exactly-one
    anchor line. The anchor is required even once the markers exist — the
    fragment is inserted BEFORE the anchor, never replacing it, so a missing or
    duplicate anchor is always a corruption (catches a hand-edit on a re-run)."""
    lines = text.splitlines()
    anchor_count = sum(1 for ln in lines if ln == ANCHOR_LINE)
    has_begin = NAV_BEGIN in lines
    has_end = NAV_END in lines
    if has_begin != has_end:
        raise SystemExit(
            "ERROR: mkdocs.yml has a partial GENERATED Guides nav marker — "
            "restore both markers or remove both"
        )
    if has_begin and has_end and lines.index(NAV_BEGIN) >= lines.index(NAV_END):
        raise SystemExit(
            "ERROR: mkdocs.yml GENERATED Guides nav markers are out of order "
            "(BEGIN must precede END)"
        )
    if anchor_count != 1:
        raise SystemExit(
            f"ERROR: mkdocs.yml expected exactly one '{ANCHOR_LINE.strip()}' anchor, "
            f"found {anchor_count}"
        )


def splice_nav_fragment(text: str, fragment: str) -> str:
    """Insert/replace the managed Guides nav fragment. First run (no markers):
    insert markers + fragment immediately before the anchor line. Subsequent
    runs: replace the lines between (inclusive) the markers. Every other line
    is preserved byte-for-byte."""
    lines = text.splitlines(keepends=False)
    block = [NAV_BEGIN, *fragment.splitlines(), NAV_END]

    if NAV_BEGIN in lines and NAV_END in lines:
        begin = lines.index(NAV_BEGIN)
        end = lines.index(NAV_END)
        new_lines = lines[:begin] + block + lines[end + 1 :]
    else:
        idx = lines.index(ANCHOR_LINE)
        new_lines = lines[:idx] + block + lines[idx:]

    trailing = "\n" if text.endswith("\n") else ""
    return "\n".join(new_lines) + trailing


def update_mkdocs_nav(decks: list[dict[str, Any]]) -> bool:
    """Read mkdocs.yml, validate, splice the fragment, write back only if
    changed. Returns True if the file was modified."""
    text = MKDOCS_YML.read_text(encoding="utf-8")
    validate_mkdocs_anchor(text)
    fragment = render_nav_fragment(decks)
    new_text = splice_nav_fragment(text, fragment)
    if new_text != text:
        MKDOCS_YML.write_text(new_text, encoding="utf-8")
        return True
    return False


# --------------------------------------------------------------------------- #
# Transcode (Story 1.3)                                                        #
# --------------------------------------------------------------------------- #
def transcode_webm_to_mp4(webm: Path, mp4: Path) -> bool:
    """Transcode webm -> mp4 (H.264 baseline, yuv420p, +faststart, no audio)
    via ffmpeg, writing to a temp file then atomically renaming. Skips when
    the mp4 exists and is newer than the webm. Returns True if a new mp4 was
    produced. Caller guarantees ffmpeg is on PATH."""
    if mp4.exists() and mp4.stat().st_mtime >= webm.stat().st_mtime:
        return False
    tmp = mp4.with_suffix(".mp4.tmp")
    argv = [
        "ffmpeg",
        "-y",
        "-i",
        str(webm),
        "-c:v",
        "libx264",
        "-profile:v",
        "baseline",
        "-level",
        "3.1",
        "-pix_fmt",
        "yuv420p",
        "-movflags",
        "+faststart",
        "-an",
        # Force the mp4 muxer — the temp output ends in ".tmp", so ffmpeg
        # cannot infer the container format from the extension (rc=234 otherwise).
        "-f",
        "mp4",
        str(tmp),
    ]
    result = subprocess.run(argv, shell=False, capture_output=True)  # noqa: S603
    if result.returncode != 0:
        if tmp.exists():
            tmp.unlink()
        print(
            f"WARN: ffmpeg failed for {webm.parent.name} (rc={result.returncode}); "
            f"leaving existing MP4 (if any) untouched",
            file=sys.stderr,
        )
        return False
    tmp.replace(mp4)
    return True


def run_transcode_pass(guides_src: Path) -> None:
    """For each deck WebM, (re)produce the MP4 if missing/stale. No-op with a
    WARN when ffmpeg is absent — the website still ships (iOS users get the
    sibling download link)."""
    if shutil.which("ffmpeg") is None:
        print(
            "WARN: ffmpeg not on PATH; skipping MP4 transcode "
            "(iOS Safari users will see the download-link fallback)",
            file=sys.stderr,
        )
        return
    for child in sorted(guides_src.iterdir(), key=lambda p: p.name):
        webm = child / LOCKED_VIDEO_NAME
        if webm.is_file():
            transcode_webm_to_mp4(webm, child / LOCKED_VIDEO_MP4)


# --------------------------------------------------------------------------- #
# Orchestration                                                                #
# --------------------------------------------------------------------------- #
def generate(transcode: bool = False) -> None:
    """Run the full generation pass. Order matters (C1-B2): transcode →
    discover → copy assets → derive availability → emit pages → emit indexes →
    prune → nav splice. Copy BEFORE emit so has_webm/has_mp4 reflect what was
    actually copied and a single run is self-consistent."""
    if transcode:
        run_transcode_pass(GUIDES_SRC)

    decks = discover_decks(GUIDES_SRC)

    WALKTHROUGHS_OUT.mkdir(parents=True, exist_ok=True)
    INDEPTH_OUT.mkdir(parents=True, exist_ok=True)
    ASSETS_OUT.mkdir(parents=True, exist_ok=True)

    # Copy assets BEFORE emitting pages (C1-B2) so has_webm/has_mp4 reflect what
    # was actually copied; a single run is self-consistent.
    copied_by_slug: dict[str, set[str]] = {}
    for deck in decks:
        src_dir = GUIDES_SRC / deck["slug"]
        dst_dir = ASSETS_OUT / deck["slug"]
        copied = copy_deck_assets(deck, src_dir, dst_dir)
        copied_by_slug[deck["slug"]] = copied
        has_webm = LOCKED_VIDEO_NAME in copied
        has_mp4 = LOCKED_VIDEO_MP4 in copied
        page = emit_deck_page(deck, has_webm, has_mp4, copied)
        (WALKTHROUGHS_OUT / f"{deck['slug']}.md").write_text(page, encoding="utf-8")

    (WALKTHROUGHS_OUT / "index.md").write_text(
        emit_walkthroughs_index(decks, copied_by_slug), encoding="utf-8"
    )
    (INDEPTH_OUT / "index.md").write_text(
        emit_indepth_index(list(LONG_FORM_GUIDES)), encoding="utf-8"
    )

    # Port the 4 long-form guides (link rewriting + presenter-comment strip).
    for basename in LONG_FORM_GUIDES:
        ported = port_long_form_guide(DOCS_SRC / basename, REPO_ROOT)
        (INDEPTH_OUT / basename).write_text(ported, encoding="utf-8")

    # Prune the generator-owned dirs to exactly the regenerated set.
    prune_all(decks, copied_by_slug)

    # Splice the managed nav fragment into mkdocs.yml.
    update_mkdocs_nav(decks)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate relyloop.com Guides pages.")
    parser.add_argument(
        "--transcode",
        action="store_true",
        help="(re)produce walkthrough.mp4 from walkthrough.webm via ffmpeg (local only)",
    )
    args = parser.parse_args(argv)
    generate(transcode=args.transcode)
    return 0


if __name__ == "__main__":
    sys.exit(main())
