#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 soundminds.ai
#
# SPDX-License-Identifier: Apache-2.0
"""Generate the PUBLIC-facing roadmap page for the RelyLoop website.

This reuses the release/status classifier in ``build_mvp1_dashboard.py`` (the
single source of truth — see CLAUDE.md) so the public roadmap can never drift
from the internal dashboards. It renders a deliberately *public-safe* view:

* the release matrix (MVP1 → GA) with a shipped / in-progress / planned badge
  derived from the feature tree, and
* per-release **capability** items (``feat_`` + ``infra_``) split into shipped
  vs planned, with ``chore_`` / ``bug_`` rolled into a single maintenance count.

It deliberately omits everything that belongs only in the internal dashboards:
P0–P3 priorities, debt notes, deferral rationale, idea-file internals, in-flight
``/impl-execute`` commands, and repo-relative source links. For exact version
numbers, readers are pointed at GitHub Releases.

Output: ``website/docs/roadmap.md`` (committed; regenerated by the pre-commit
hook when ``planned_features/`` or ``implemented_features/`` change). Output is
deterministic — no timestamps or clock reads — so re-running on an unchanged
tree is a no-op and never causes commit churn.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Import the canonical classifier from the sibling generator. Path-insert keeps
# this working regardless of the caller's cwd (pre-commit, CI, manual run).
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_mvp1_dashboard import (  # noqa: E402
    ROADMAP_RELEASES,
    Feature,
    _maybe_write,
    load_all,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "website" / "docs" / "roadmap.md"

RELEASES_URL = "https://github.com/SoundMindsAI/relyloop/releases"
COMPARISON_URL = "https://github.com/SoundMindsAI/relyloop/blob/main/docs/07_research/comparison.md"

# Capability-bearing work types we itemize on the public roadmap. chore_/bug_
# are maintenance noise for a public audience — rolled into a count instead.
CAPABILITY_PREFIXES = frozenset({"feat", "infra", "epic"})

# Acronyms `.title()` mangles — restored for a polished display label.
_ACRONYMS = {
    "Ubi": "UBI",
    "Ui": "UI",
    "Llm": "LLM",
    "Pr": "PR",
    "Api": "API",
    "Es": "ES",
    "Ci": "CI",
    "Ga": "GA",
    "Ltr": "LTR",
    "Srw": "SRW",
    "Db": "DB",
}

_STATE_BADGE = {
    "shipped": "✅ Shipped",
    "in_progress": "🟡 In progress",
    "planned": "⬜ Planned",
}


def _pretty(display_name: str) -> str:
    """Fix acronym casing in a Feature.display_name (already Title Cased)."""
    return " ".join(_ACRONYMS.get(tok, tok) for tok in display_name.split())


def _release_state(items: list[Feature]) -> str:
    has_shipped = any(f.location == "implemented" for f in items)
    has_planned = any(f.location == "planned" for f in items)
    if has_shipped and has_planned:
        return "in_progress"
    if has_shipped:
        return "shipped"
    return "planned"


def _capability_items(items: list[Feature], *, shipped: bool) -> list[str]:
    loc = "implemented" if shipped else "planned"
    names = sorted(
        _pretty(f.display_name)
        for f in items
        if f.prefix in CAPABILITY_PREFIXES and f.location == loc
    )
    return names


def render_markdown(features: list[Feature]) -> str:
    by_release: dict[str, list[Feature]] = {}
    for f in features:
        by_release.setdefault(f.release, []).append(f)

    lines: list[str] = [
        "<!-- AUTO-GENERATED by scripts/build_public_roadmap.py — do not edit by hand.",
        "     Regenerated from docs/00_overview/{planned,implemented}_features/ via the",
        "     pre-commit hook. To change content, change the feature tree or the script. -->",
        "",
        "# Roadmap",
        "",
        '!!! abstract "Summary"',
        "    Where RelyLoop is in its release plan — generated directly from the",
        "    project's own feature tree, so it stays honest. **MVP1 has shipped and",
        "    MVP2 is in progress** (the Apache Solr adapter and UBI judgments are",
        "    already in). For exact version numbers and per-release notes, see",
        f"    [GitHub Releases]({RELEASES_URL}).",
        "",
        "## Release matrix",
        "",
        "| Release | Theme | Status |",
        "|---|---|---|",
    ]

    states: dict[str, str] = {}
    for tag, label, theme in ROADMAP_RELEASES:
        items = by_release.get(tag, [])
        state = _release_state(items) if items else "planned"
        states[tag] = state
        lines.append(f"| {label} | {theme} | {_STATE_BADGE[state]} |")
    lines.append("")

    for tag, label, theme in ROADMAP_RELEASES:
        items = by_release.get(tag, [])
        state = states[tag]
        lines.append(f"## {label} — {theme} &nbsp; {_STATE_BADGE[state]}")
        lines.append("")

        # A *released* milestone (fully shipped) doesn't need its dozens of
        # folders itemized on a public roadmap — the detail lives in Releases.
        # The useful signal is the IN-PROGRESS release, where "what's landed
        # vs what's left" actually tells a reader where the project is. Planned
        # releases with nothing filed yet get a one-liner too.
        if state == "shipped":
            lines.append(
                f"✅ **Shipped.** Milestone theme: *{theme}*. See "
                f"[GitHub Releases]({RELEASES_URL}) for the full feature list."
            )
            lines.append("")
            continue

        shipped = _capability_items(items, shipped=True)
        planned = _capability_items(items, shipped=False)

        if state == "in_progress":
            if shipped:
                lines.append("**Landed so far**")
                lines.append("")
                lines.extend(f"- ✅ {n}" for n in shipped)
                lines.append("")
            if planned:
                lines.append("**Still ahead**")
                lines.append("")
                lines.extend(f"- 🟡 {n}" for n in planned)
                lines.append("")
            maintenance = sum(1 for f in items if f.prefix in {"chore", "bug"})
            if maintenance:
                lines.append(
                    f"_Plus {maintenance} maintenance &amp; fix item"
                    f"{'s' if maintenance != 1 else ''}, not itemized here._"
                )
                lines.append("")
            continue

        # state == "planned"
        if planned:
            lines.append(f"⬜ **Planned** — *{theme}*. Scoped capabilities:")
            lines.append("")
            lines.extend(f"- ⬜ {n}" for n in planned)
            lines.append("")
        else:
            lines.append(
                f"⬜ **Planned** — *{theme}*. Themed in the release matrix; "
                "individual features not yet filed."
            )
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Backlog items (multi-Git providers, multi-tenancy, multi-LLM provider "
        "SDKs, LTR training, production monitoring) are tracked but not scheduled "
        "into a release. See the "
        f"[comparison doc]({COMPARISON_URL}) "
        "for scope and non-goals."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    features = load_all()
    content = render_markdown(features)
    changed = _maybe_write(OUTPUT, content)
    rel = OUTPUT.relative_to(REPO_ROOT)
    print(f"{'wrote' if changed else 'unchanged'}: {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
