#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 soundminds.ai
#
# SPDX-License-Identifier: Apache-2.0
"""Generate the public roadmap page for the RelyLoop website.

RelyLoop develops in the open, so this page maximizes information to the
community: it reuses the release/status classifier in ``build_mvp1_dashboard.py``
(the single source of truth — see CLAUDE.md) and renders every release's work,
with **each item linked to its folder on GitHub** (and to its merge PR when one
exists). Features are foregrounded; infrastructure and maintenance/fixes go in
collapsible sections so the page stays scannable without hiding anything. Each
release also links to its full internal dashboard (priorities, dependencies,
debt) for readers who want the complete engineering view.

Output: ``website/docs/roadmap.md`` (committed; regenerated by the pre-commit
hook when ``planned_features/`` or ``implemented_features/`` change). Output is
deterministic — no timestamps or clock reads — so re-running on an unchanged
tree is a no-op and never causes commit churn.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Import the canonical classifier from the sibling generator. Path-insert keeps
# this working regardless of the caller's cwd (pre-commit, CI, manual run).
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_mvp1_dashboard import (  # noqa: E402
    ROADMAP_RELEASES,
    Feature,
    _maybe_write,
    load_all,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "website" / "docs" / "roadmap.md"

REPO_URL = "https://github.com/SoundMindsAI/relyloop"
TREE_URL = f"{REPO_URL}/tree/main/"
BLOB_URL = f"{REPO_URL}/blob/main/"
RELEASES_URL = f"{REPO_URL}/releases"
COMPARISON_URL = f"{BLOB_URL}docs/07_research/comparison.md"

# Acronyms `.title()` mangles — restored for a polished display label.
_ACRONYMS = {
    "Ubi": "UBI",
    "Ui": "UI",
    "Llm": "LLM",
    "Pr": "PR",
    "Api": "API",
    "Es": "ES",
    "Ci": "CI",
    "Ga": "GA",
    "Ltr": "LTR",
    "Srw": "SRW",
    "Db": "DB",
    "Fts": "FTS",
    "Crud": "CRUD",
    "E2E": "E2E",
    "Arq": "Arq",
}

_STATE_BADGE = {
    "shipped": "✅ Shipped",
    "in_progress": "🟡 In progress",
    "planned": "⬜ Planned",
}


def _pretty(display_name: str) -> str:
    """Fix acronym casing in a Feature.display_name (already Title Cased)."""
    return " ".join(_ACRONYMS.get(tok, tok) for tok in display_name.split())


def _release_state(items: list[Feature]) -> str:
    has_shipped = any(f.location == "implemented" for f in items)
    has_planned = any(f.location == "planned" for f in items)
    if has_shipped and has_planned:
        return "in_progress"
    if has_shipped:
        return "shipped"
    return "planned"


def _gh_folder_url(f: Feature) -> str:
    return TREE_URL + f.path.relative_to(REPO_ROOT).as_posix()


def _bullet(f: Feature, release_state: str, *, indent: str = "") -> str:
    if f.location == "implemented":
        mark = "✅"
    else:
        mark = "🟡" if release_state == "in_progress" else "⬜"
    line = f"{indent}- {mark} [{_pretty(f.display_name)}]({_gh_folder_url(f)})"
    # Only link the merge PR for shipped items. A planned feature's pr_number is
    # a *referenced* PR scraped from its idea/spec (a related/originating PR),
    # not its own merge — linking it would imply the feature already shipped.
    if f.pr_number and f.location == "implemented":
        line += f" · [#{f.pr_number}]({REPO_URL}/pull/{f.pr_number})"
    return line


def _sort_key(f: Feature) -> tuple[int, str]:
    # Shipped first, then planned; alphabetical within each.
    return (0 if f.location == "implemented" else 1, f.display_name.lower())


def _dashboard_link(tag: str) -> str | None:
    name = f"{tag.upper()}_DASHBOARD.md"
    if (REPO_ROOT / "docs" / "00_overview" / name).exists():
        return f"{BLOB_URL}docs/00_overview/{name}"
    return None


def _details_block(title: str, features: list[Feature], state: str) -> list[str]:
    if not features:
        return []
    out = [f'??? note "{title} ({len(features)})"', ""]
    for f in sorted(features, key=_sort_key):
        out.append(_bullet(f, state, indent="    "))
    out.append("")
    return out


def render_markdown(features: list[Feature]) -> str:
    by_release: dict[str, list[Feature]] = {}
    for f in features:
        by_release.setdefault(f.release, []).append(f)

    lines: list[str] = [
        "<!-- AUTO-GENERATED by scripts/build_public_roadmap.py — do not edit by hand.",
        "     Regenerated from docs/00_overview/{planned,implemented}_features/ via the",
        "     pre-commit hook. To change content, change the feature tree or the script. -->",
        "",
        "# Roadmap",
        "",
        '!!! abstract "Summary"',
        "    Where RelyLoop is in its release plan — generated directly from the",
        "    project's own feature tree, so it stays honest. **MVP1 has shipped and",
        "    MVP2 is in progress.** RelyLoop develops in the open: every item below",
        "    links to its folder on GitHub (and to its merge PR, where one exists).",
        "    For exact versions see "
        f"[GitHub Releases]({RELEASES_URL}); for the full engineering view",
        "    (priorities, dependencies, debt) follow the per-release dashboard links.",
        "",
        "## Release matrix",
        "",
        "| Release | Theme | Status |",
        "|---|---|---|",
    ]

    states: dict[str, str] = {}
    for tag, label, theme in ROADMAP_RELEASES:
        items = by_release.get(tag, [])
        state = _release_state(items) if items else "planned"
        states[tag] = state
        lines.append(f"| {label} | {theme} | {_STATE_BADGE[state]} |")
    lines.append("")

    for tag, label, theme in ROADMAP_RELEASES:
        items = by_release.get(tag, [])
        state = states[tag]
        lines.append(f"## {label} — {theme} &nbsp; {_STATE_BADGE[state]}")
        lines.append("")

        if not items:
            lines.append(
                f"⬜ **Planned** — *{theme}*. Themed in the release matrix; "
                "individual features not yet filed."
            )
            lines.append("")
            continue

        feats = [f for f in items if f.prefix == "feat"]
        infra = [f for f in items if f.prefix in {"infra", "epic"}]
        maint = [f for f in items if f.prefix in {"chore", "bug"}]

        if feats:
            lines.append("**Features**")
            lines.append("")
            lines.extend(_bullet(f, state) for f in sorted(feats, key=_sort_key))
            lines.append("")
        lines.extend(_details_block("Infrastructure & tooling", infra, state))
        lines.extend(_details_block("Maintenance & fixes", maint, state))

        dash = _dashboard_link(tag)
        if dash:
            lines.append(f"→ Full engineering view: [{label} dashboard]({dash})")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Backlog items (multi-Git providers, multi-tenancy, multi-LLM provider "
        "SDKs, LTR training, production monitoring) are tracked but not scheduled "
        "into a release. See the "
        f"[comparison doc]({COMPARISON_URL}) "
        "for scope and non-goals, and the "
        f"[backlog dashboard]({BLOB_URL}docs/00_overview/BACKLOG_DASHBOARD.md) "
        "for the filed ideas."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    features = load_all()
    content = render_markdown(features)
    changed = _maybe_write(OUTPUT, content)
    rel = OUTPUT.relative_to(REPO_ROOT)
    print(f"{'wrote' if changed else 'unchanged'}: {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
