"""Digest-narrative prompt loader + renderer (feat_digest_proposal Story 1.3).

Mirrors :mod:`backend.app.llm.prompt_loader` exactly — same module-level
``SandboxedEnvironment(autoescape=True)``, same ``lru_cache(maxsize=1)``
loader, same repo-root path resolution. Differs only in:

* The two prompt files loaded (``digest_narrative.system.md`` +
  ``digest_narrative.user.jinja``).
* The render signature, which accepts study-summary inputs + the
  deterministically computed ``recommended_config`` + ``dropped_template_params``
  (per cycle-1 F5 / cycle-2 F1, F2 — the LLM does NOT generate the config;
  it RECEIVES it as input and describes it).
* The ``include_recommendation: bool`` toggle (cycle-3 F3) for the
  capability-fallback path. When False, the renderer emits the
  ``<degraded_mode>`` block and skips the ``<recommended_config>`` +
  ``<dropped_template_params>`` blocks; the worker calls OpenAI without
  ``response_format`` and treats the response text as the narrative.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

from jinja2.sandbox import SandboxedEnvironment

PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts"
"""Repo-root ``prompts/`` directory. Same resolution as the judgments loader:
``backend/app/llm/digest_prompt.py`` → ``parents[3]`` is the repo root."""


@dataclass(frozen=True)
class DigestPromptBundle:
    """Cached snapshot of the two on-disk digest prompt artifacts."""

    system_prompt: str
    user_template_src: str


@lru_cache(maxsize=1)
def load_digest_prompts() -> DigestPromptBundle:
    """Read and cache the two digest-narrative prompt files.

    Operator edits require a worker restart (same convention as the
    judgments loader). The prompts directory is part of the deployed
    image so a hot-reload would only matter in development.
    """
    system_path = PROMPTS_DIR / "digest_narrative.system.md"
    user_path = PROMPTS_DIR / "digest_narrative.user.jinja"
    return DigestPromptBundle(
        system_prompt=system_path.read_text(encoding="utf-8"),
        user_template_src=user_path.read_text(encoding="utf-8"),
    )


_SANDBOX_ENV = SandboxedEnvironment(keep_trailing_newline=True, autoescape=True)
"""Module-level sandbox. ``autoescape=True`` HTML-escapes every variable
substitution; the XML-style ``<study>`` / ``<top_trials>`` / ``<recommended_config>``
delimiters survive only because they're template literals, not substituted
content. Mirrors the prompt_loader.py contract (cycle-5 C5-F2 of
feat_llm_judgments)."""


def render_digest_user_prompt(
    *,
    study_name: str,
    cluster_name: str,
    target: str,
    query_set_name: str,
    query_count: int,
    judgment_list_name: str,
    rubric_summary: str,
    baseline_metric: float | None,
    achieved_metric: float,
    top_trials: Sequence[Mapping[str, Any]],
    parameter_importance: Mapping[str, float],
    recommended_config: Mapping[str, Any],
    dropped_template_params: Sequence[str],
    include_recommendation: bool = True,
    confidence: Mapping[str, Any] | None = None,
    parent_search_space: Mapping[str, Any] | None = None,
    parent_template_declared_params: Mapping[str, str] | None = None,
    available_templates: Sequence[Mapping[str, Any]] | None = None,
) -> str:
    """Render the per-study user message for the digest narrative call.

    Args:
        study_name: study name (verbatim into the ``<study>`` block).
        cluster_name: cluster's friendly name (e.g. ``products-prod-es``).
        target: index / collection name on the cluster.
        query_set_name: query-set name; surfaces in the ``<study>`` block.
        query_count: count of queries in the query set; rendered alongside the name.
        judgment_list_name: judgment-list friendly name.
        rubric_summary: short summary of the active rubric (one or two lines).
        baseline_metric: ``studies.baseline_metric`` (None if no baseline
            trial — rendered as the literal string ``"N/A"`` by the template).
        achieved_metric: ``studies.best_metric``.
        top_trials: ``[{"number": int, "params": dict, "primary_metric": float}, ...]``
            — the top-10 by primary_metric DESC.
        parameter_importance: ``optuna.importance.get_param_importances`` output.
        recommended_config: WORKER-computed (best-trial params filtered to
            currently-declared template params). NOT generated by the LLM.
        dropped_template_params: best-trial param keys absent from the
            current template's ``declared_params`` (template drift).
            Empty when there's no drift.
        include_recommendation: cycle-3 F3 toggle. ``True`` (default) emits
            the full structured prompt; ``False`` emits the degraded /
            narrative-only variant for the capability-fallback path.
        confidence: serialized ``ConfidenceShape`` (via
            ``ConfidenceShape.model_dump()``) per feat_pr_metric_confidence
            FR-6. ``None`` (default) skips both the ``<confidence>`` and
            ``<per_query_outcomes>`` jinja blocks; a partial shape (some
            sub-fields ``None``) emits only the populated sub-lines via the
            template's per-sub-field ``{% if %}`` guards.
        parent_search_space: feat_digest_executable_followups Story 2.2 —
            the parent study's ``search_space`` JSONB body, rendered into
            ``<parent_search_space>`` so the LLM can transform it into
            ``narrow`` / ``widen`` follow-up proposals (FR-8). ``None``
            (default) skips the block — the structured-followup feature
            is opt-in at the worker call site.
        parent_template_declared_params: feat_digest_executable_followups_swap_template
            Story 2.2 (FR-6 / FR-7) — the parent query template's
            ``declared_params`` map. Rendered into ``<parent_template_declared_params>``
            so the LLM can decide whether a ``swap_template`` follow-up
            makes sense. ``None`` / empty skips the block.
        available_templates: feat_digest_executable_followups_swap_template
            Story 2.2 (FR-6 / FR-7) — a list of alternative templates the
            worker fetched from the catalogue (filtered to the parent
            cluster's ``engine_type`` and excluding the parent template).
            Each entry has ``{id, name, version, declared_params}``.
            Rendered into ``<available_templates>``; when ``None`` /
            empty the LLM is implicitly instructed (via the system prompt)
            to skip ``swap_template`` followups entirely.

    Returns:
        The rendered user message string, ready to send as the OpenAI
        ``messages[1].content``.
    """
    bundle = load_digest_prompts()
    template = _SANDBOX_ENV.from_string(bundle.user_template_src)
    return template.render(
        study_name=study_name,
        cluster_name=cluster_name,
        target=target,
        query_set_name=query_set_name,
        query_count=query_count,
        judgment_list_name=judgment_list_name,
        rubric_summary=rubric_summary,
        baseline_metric=baseline_metric,
        achieved_metric=achieved_metric,
        top_trials=top_trials,
        parameter_importance=parameter_importance,
        recommended_config=recommended_config,
        dropped_template_params=dropped_template_params,
        include_recommendation=include_recommendation,
        confidence=confidence,
        parent_search_space=parent_search_space,
        parent_template_declared_params=parent_template_declared_params,
        available_templates=available_templates,
    )


def render_digest_system_prompt(*, include_recommendation: bool = True) -> str:
    """Return the bundle's system prompt verbatim.

    For MVP1 the same system prompt is used for both the structured and
    degraded paths — the user prompt's ``{% if not include_recommendation %}``
    branch carries the degraded-mode framing. The ``include_recommendation``
    parameter is reserved for a future split-prompt design.
    """
    del include_recommendation  # reserved hook
    return load_digest_prompts().system_prompt
