"""Contract test placeholder for ``/api/v1/clusters`` (Story 5.1).

The full contract assertions (spec §7.5 error codes, response shapes) run
in the integration layer at ``backend/tests/integration/test_clusters_api.py``,
which exercises the real FastAPI app + DB + Compose Elasticsearch.

This module exists for inventory parity with spec §14 — the surface here is
guaranteed by Pydantic models in ``backend/app/api/v1/schemas.py`` (Literal
types and ``Field(...)`` validators) and the OpenAPI schema generated by
FastAPI from those models. A separate spec-§7.5 error-code contract test
lives at ``test_error_codes.py``.
"""

from __future__ import annotations

from backend.app.adapters.protocol import TargetInfo
from backend.app.api.v1.schemas import (
    ClusterDetail,
    ClusterListResponse,
    ClusterSummary,
    CreateClusterRequest,
    HealthCheckResult,
    RunQueryRequest,
    RunQueryResponse,
    TargetListResponse,
)


def test_response_schemas_importable() -> None:
    """Smoke test: every documented response model is importable."""
    assert ClusterDetail is not None
    assert ClusterListResponse is not None
    assert ClusterSummary is not None
    assert CreateClusterRequest is not None
    assert HealthCheckResult is not None
    assert RunQueryRequest is not None
    assert RunQueryResponse is not None
    assert TargetListResponse is not None


def test_target_list_response_is_bare_data_shape() -> None:
    """feat_create_study_target_autocomplete B2 / spec §7.1: TargetListResponse
    is the bare ``{ data: TargetInfo[] }`` shape — NO ``next_cursor`` or
    ``has_more`` fields.

    The decision is documented in feature_spec.md §7.1 "pagination shape
    rationale" (cycle-1 GPT-5.5 review fix): EntitySelectListPage<T>'s
    cursor fields are optional, so the bare data shape consumes correctly
    on the frontend without pretending to be a cursor endpoint.
    """
    declared = set(TargetListResponse.model_fields.keys())
    assert declared == {"data"}, f"unexpected extra fields: {declared - {'data'}}"

    # Round-trip a happy-path payload through the model to lock the shape.
    payload = {"data": [{"name": "products", "doc_count": 42}]}
    resp = TargetListResponse.model_validate(payload)
    assert resp.data == [TargetInfo(name="products", doc_count=42)]
    # Serialized form matches the wire contract.
    assert resp.model_dump() == payload


def test_create_cluster_request_validates_scheme() -> None:
    """``base_url`` must use http or https."""
    import pytest
    from pydantic import ValidationError

    with pytest.raises(ValidationError, match="http or https"):
        CreateClusterRequest(
            name="cluster",
            engine_type="elasticsearch",
            environment="dev",
            base_url="ftp://elasticsearch:9200",
            auth_kind="es_basic",
            credentials_ref="ref",
        )


def _make_cluster_request(**overrides: object) -> CreateClusterRequest:
    """Build a minimal valid CreateClusterRequest for validator-focused tests."""
    fields: dict[str, object] = {
        "name": "cluster",
        "engine_type": "elasticsearch",
        "environment": "dev",
        "base_url": "http://elasticsearch:9200",
        "auth_kind": "es_basic",
        "credentials_ref": "ref",
    }
    fields.update(overrides)
    return CreateClusterRequest(**fields)


class TestTargetFilterValidator:
    """feat_cluster_target_filter Story B3 — request validator (FR-2 + Finding #5)."""

    def test_omitted_defaults_to_none(self) -> None:
        req = _make_cluster_request()
        assert req.target_filter is None

    def test_valid_pattern_accepted(self) -> None:
        req = _make_cluster_request(target_filter="products*")
        assert req.target_filter == "products*"

    def test_padded_string_strips_to_canonical(self) -> None:
        """Finding #5: mode='before' validator strips before min/max_length run."""
        req = _make_cluster_request(target_filter="  products*  ")
        assert req.target_filter == "products*"

    def test_padded_at_max_length_boundary_passes(self) -> None:
        """Padded 256-char filter MUST pass — proves max_length sees stripped value.

        Without mode='before' the leading/trailing whitespace would push the
        wire length past 256 and falsely 422.
        """
        padded = "  " + ("x" * 256) + "  "
        req = _make_cluster_request(target_filter=padded)
        assert req.target_filter == "x" * 256

    def test_empty_string_rejected(self) -> None:
        import pytest
        from pydantic import ValidationError

        with pytest.raises(ValidationError):
            _make_cluster_request(target_filter="")

    def test_whitespace_only_rejected(self) -> None:
        """Whitespace strips to empty, then min_length=1 catches it."""
        import pytest
        from pydantic import ValidationError

        with pytest.raises(ValidationError):
            _make_cluster_request(target_filter="   ")

    def test_over_256_chars_rejected(self) -> None:
        import pytest
        from pydantic import ValidationError

        with pytest.raises(ValidationError):
            _make_cluster_request(target_filter="x" * 257)


def test_run_query_request_caps_top_k_at_1000() -> None:
    """``top_k`` is bounded at 1000 (spec FR-6 / Decision Log 2026-05-09)."""
    import pytest
    from pydantic import ValidationError

    with pytest.raises(ValidationError):
        RunQueryRequest(target="products", query_dsl={}, top_k=1001)
