"""Contract test placeholder for ``/api/v1/clusters`` (Story 5.1).

The full contract assertions (spec §7.5 error codes, response shapes) run
in the integration layer at ``backend/tests/integration/test_clusters_api.py``,
which exercises the real FastAPI app + DB + Compose Elasticsearch.

This module exists for inventory parity with spec §14 — the surface here is
guaranteed by Pydantic models in ``backend/app/api/v1/schemas.py`` (Literal
types and ``Field(...)`` validators) and the OpenAPI schema generated by
FastAPI from those models. A separate spec-§7.5 error-code contract test
lives at ``test_error_codes.py``.
"""

from __future__ import annotations

from backend.app.api.v1.schemas import (
    ClusterDetail,
    ClusterListResponse,
    ClusterSummary,
    CreateClusterRequest,
    HealthCheckResult,
    RunQueryRequest,
    RunQueryResponse,
)


def test_response_schemas_importable() -> None:
    """Smoke test: every documented response model is importable."""
    assert ClusterDetail is not None
    assert ClusterListResponse is not None
    assert ClusterSummary is not None
    assert CreateClusterRequest is not None
    assert HealthCheckResult is not None
    assert RunQueryRequest is not None
    assert RunQueryResponse is not None


def test_create_cluster_request_validates_scheme() -> None:
    """``base_url`` must use http or https."""
    import pytest
    from pydantic import ValidationError

    with pytest.raises(ValidationError, match="http or https"):
        CreateClusterRequest(
            name="cluster",
            engine_type="elasticsearch",
            environment="dev",
            base_url="ftp://elasticsearch:9200",
            auth_kind="es_basic",
            credentials_ref="ref",
        )


def test_run_query_request_caps_top_k_at_1000() -> None:
    """``top_k`` is bounded at 1000 (spec FR-6 / Decision Log 2026-05-09)."""
    import pytest
    from pydantic import ValidationError

    with pytest.raises(ValidationError):
        RunQueryRequest(target="products", query_dsl={}, top_k=1001)
