# SPDX-FileCopyrightText: 2026 soundminds.ai
#
# SPDX-License-Identifier: Apache-2.0

"""`/healthz` contract tests (infra_foundation Story 3.2 / spec §7.5).

Asserts the JSON response shape against the OpenAPI schema generated by
FastAPI, and verifies the SERVICE_UNAVAILABLE error code surface for the
degraded path per spec §7.5 + api-conventions.md "Standard error codes".
"""

from __future__ import annotations

from collections.abc import AsyncGenerator
from typing import Literal
from unittest.mock import AsyncMock, MagicMock

import httpx
import pytest
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient
from redis.asyncio import Redis

from backend.app.api import health, probes
from backend.app.api.errors import install_exception_handlers
from backend.app.api.middleware import RequestIDMiddleware
from backend.app.core.settings import Settings, get_settings


def _make_settings(tmp_path, monkeypatch: pytest.MonkeyPatch) -> Settings:
    """Build Settings with stubbed required-secret files.

    Uses ``monkeypatch.setenv`` (not direct ``os.environ`` mutation) so the
    Alembic subprocess in ``test_migrations.py`` doesn't inherit a polluted
    DATABASE_URL_FILE pointing at this test's stub URL.
    """
    db_url_file = tmp_path / "db_url"
    db_url_file.write_text("postgresql+asyncpg://x:y@localhost/test")
    pw_file = tmp_path / "pw"
    pw_file.write_text("test")
    monkeypatch.setenv("DATABASE_URL_FILE", str(db_url_file))
    monkeypatch.setenv("POSTGRES_PASSWORD_FILE", str(pw_file))
    return Settings()


def _mock_redis() -> Redis:
    client = MagicMock(spec=Redis)
    client.ping = AsyncMock(return_value=True)
    client.get = AsyncMock(return_value=None)
    return client


def _mock_httpx_client() -> httpx.AsyncClient:
    client = MagicMock(spec=httpx.AsyncClient)

    async def _get(url: str) -> httpx.Response:
        return httpx.Response(status_code=200, request=httpx.Request("GET", url))

    client.get = _get
    return client


def _override_probes(
    app: FastAPI,
    monkeypatch: pytest.MonkeyPatch,
    *,
    db_status: Literal["ok", "down"] = "ok",
    redis_status: Literal["ok", "down"] = "ok",
    es_status: Literal["reachable", "unreachable"] = "reachable",
    os_status: Literal["reachable", "unreachable"] = "reachable",
    openai_state: Literal["configured", "missing_key", "incapable"] = "missing_key",
) -> None:
    async def _probe_db(_engine):
        return db_status

    async def _probe_redis(_client):
        return redis_status

    async def _probe_es(_client, _url):
        return es_status

    async def _probe_os(_client, _url):
        return os_status

    def _probe_openai(_key, _cap):
        return openai_state

    async def _probe_clusters(_db, _redis):
        return probes.ClusterAggregateHealth(registered=0, healthy=0, unreachable=0)

    monkeypatch.setattr(probes, "probe_db", _probe_db)
    monkeypatch.setattr(probes, "probe_redis", _probe_redis)
    monkeypatch.setattr(probes, "probe_elasticsearch", _probe_es)
    monkeypatch.setattr(probes, "probe_opensearch", _probe_os)
    monkeypatch.setattr(probes, "probe_openai_state", _probe_openai)
    monkeypatch.setattr(probes, "probe_registered_clusters", _probe_clusters)
    app.dependency_overrides[health.get_redis_client] = lambda: _mock_redis()
    app.dependency_overrides[health.get_es_client] = lambda: _mock_httpx_client()
    # Story 3.5: /healthz now takes a db: AsyncSession dep. The
    # probe_registered_clusters override above ignores its `db` argument so
    # we can stub the dependency with a no-op generator.
    from backend.app.db.session import get_db as _real_get_db

    async def _stub_db():
        yield None

    app.dependency_overrides[_real_get_db] = _stub_db


@pytest.fixture
def app(tmp_path, monkeypatch: pytest.MonkeyPatch) -> FastAPI:
    test_app = FastAPI(title="RelyLoop test", version="0.1.0")
    install_exception_handlers(test_app)
    test_app.add_middleware(RequestIDMiddleware)
    test_app.include_router(health.router)
    settings = _make_settings(tmp_path, monkeypatch)
    test_app.dependency_overrides[get_settings] = lambda: settings
    return test_app


@pytest.fixture
async def client(app: FastAPI) -> AsyncGenerator[AsyncClient]:
    transport = ASGITransport(app=app, raise_app_exceptions=False)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        yield c


# ---------------------------------------------------------------------------
# OpenAPI schema conformance
# ---------------------------------------------------------------------------


class TestHealthOpenAPISchema:
    """`GET /healthz` must be advertised at the documented contract."""

    async def test_endpoint_listed_in_openapi(self, app: FastAPI) -> None:
        schema = app.openapi()
        assert "/healthz" in schema["paths"], "GET /healthz missing from OpenAPI schema"
        op = schema["paths"]["/healthz"]["get"]
        # Both 200 and 503 should be advertised
        assert "200" in op["responses"], "200 response missing from /healthz schema"
        assert "503" in op["responses"], "503 response missing from /healthz schema"

    async def test_response_schema_matches_documented_keys(
        self, app: FastAPI, client: AsyncClient, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        _override_probes(app, monkeypatch)
        resp = await client.get("/healthz")
        body = resp.json()
        # Per spec §7.3 — required top-level keys
        required = {
            "status",
            "subsystems",
            "openai_endpoint",
            "openai_capabilities",
            "version",
            "uptime_seconds",
        }
        assert required.issubset(body.keys()), f"missing keys: {required - body.keys()}"
        # subsystems shape matches spec §7.4 + Story 3.5 elasticsearch_clusters
        # + infra_adapter_solr Story A12 (solr subsystem probe).
        assert set(body["subsystems"].keys()) == {
            "db",
            "redis",
            "openai",
            "elasticsearch",
            "opensearch",
            "solr",
            "elasticsearch_clusters",
        }
        assert set(body["subsystems"]["elasticsearch_clusters"].keys()) == {
            "registered",
            "healthy",
            "unreachable",
        }
        # openai_capabilities shape per bug_openai_capability_check spec §8.2 —
        # five required keys; models_endpoint_status_code is required-but-nullable.
        assert set(body["openai_capabilities"].keys()) == {
            "models_endpoint",
            "models_endpoint_status_code",
            "chat",
            "function_calling",
            "structured_output",
        }
        # Key always present even when value is null (cache-miss case here).
        assert body["openai_capabilities"]["models_endpoint_status_code"] is None

    async def test_openai_capabilities_schema_advertises_required_and_enum(
        self, app: FastAPI
    ) -> None:
        """Spec FR-5 / D-1 / D-3 / D-8: the OpenAPI schema must advertise the
        new ``OpenAICapabilities.models_endpoint`` field with its three-literal
        enum and the ``models_endpoint_status_code`` field as required-but-
        nullable.
        """
        schema = app.openapi()
        cap_schema = schema["components"]["schemas"]["OpenAICapabilities"]
        # Both new fields must be in `required` (not optional).
        assert "models_endpoint" in cap_schema["required"], cap_schema["required"]
        assert "models_endpoint_status_code" in cap_schema["required"], cap_schema["required"]
        # models_endpoint enum is exactly the three literals from §19 D-1.
        models_endpoint_prop = cap_schema["properties"]["models_endpoint"]
        assert set(models_endpoint_prop["enum"]) == {"ok", "fail", "untested"}, models_endpoint_prop
        # models_endpoint_status_code is nullable (Pydantic v2 emits anyOf).
        status_code_prop = cap_schema["properties"]["models_endpoint_status_code"]
        any_of = status_code_prop.get("anyOf") or []
        any_of_types = {entry.get("type") for entry in any_of}
        assert any_of_types == {"integer", "null"}, status_code_prop


# ---------------------------------------------------------------------------
# 200 path — fully healthy
# ---------------------------------------------------------------------------


class TestHealthyResponse:
    async def test_all_healthy_returns_200_with_status_ok(
        self, app: FastAPI, client: AsyncClient, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        _override_probes(app, monkeypatch)
        resp = await client.get("/healthz")
        assert resp.status_code == 200
        body = resp.json()
        assert body["status"] == "ok"
        # Subsystem enum values must match the spec §7.4 allowlist
        assert body["subsystems"]["db"] in {"ok", "down"}
        assert body["subsystems"]["redis"] in {"ok", "down"}
        assert body["subsystems"]["openai"] in {"configured", "missing_key", "incapable"}
        assert body["subsystems"]["elasticsearch"] in {"reachable", "unreachable"}
        assert body["subsystems"]["opensearch"] in {"reachable", "unreachable"}


# ---------------------------------------------------------------------------
# 503 path — error code SERVICE_UNAVAILABLE per spec §7.5
# ---------------------------------------------------------------------------


class TestDegradedResponse:
    """spec §7.5 maps the degraded path to SERVICE_UNAVAILABLE."""

    async def test_degraded_returns_503(
        self, app: FastAPI, client: AsyncClient, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        _override_probes(app, monkeypatch, db_status="down")
        resp = await client.get("/healthz")
        assert resp.status_code == 503
        body = resp.json()
        assert body["status"] == "degraded"
        # /healthz returns the same body shape on 503; the SERVICE_UNAVAILABLE
        # code applies to the HTTP status line + the operator-visible signal.
        # api-conventions.md does NOT require /healthz to use the standard
        # error-envelope shape (it's an operator probe, not an API resource).
        assert body["subsystems"]["db"] == "down"

    async def test_503_payload_keeps_documented_shape(
        self, app: FastAPI, client: AsyncClient, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Even on 503, the body MUST follow spec §7.3 shape (not a generic envelope)."""
        _override_probes(app, monkeypatch, redis_status="down")
        resp = await client.get("/healthz")
        body = resp.json()
        assert set(body.keys()) >= {
            "status",
            "subsystems",
            "openai_endpoint",
            "openai_capabilities",
            "version",
            "uptime_seconds",
        }
